### ISSUE TITLE
chrome 浏览器报错，怎么解决这个问题呢？

### ISSUE THREAD

**Issue by wangyoukun** [kkHAIKE/fake115#1]
VM1100:2 Uncaught InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

**Comment by kkHAIKE** [comment]
什么版本的chrome呢。。。
每次都出现吗？
这个是atob函数啊很奇怪应该是自带的

**Comment by wangyoukun** [comment]
Google Chrome 版本 50.0.2661.102 m  每次都出现 目前还没用这个浏览器正常登录进去过

**Comment by kkHAIKE** [comment]
使用了tampermonkey插件吗
用最新版本的chrome试试看呢

**Comment by Renlong-Yin** [comment]
你好，使用贵脚本遇到了`非法登录`的提示，Chrome 53 Dev + Tampermonkey，请查证。

**Comment by kkHAIKE** [comment]
53 的详细版本

**Comment by Renlong-Yin** [comment]
@kkHAIKE 
53.0.2774.3 dev (64-bit)

**Comment by kkHAIKE** [comment]
我用相同版本测试通过。
看下控制台有什么输出吗

**Comment by Renlong-Yin** [comment]
@kkHAIKE 今測試貴腳本使用正常且已成功登錄
