### ISSUE TITLE
实用脚本 请上传Greasy Fork

### ISSUE THREAD

**Issue by catshitzhou** [kkHAIKE/fake115#10]
可以使用 非常感谢
不过Greasy Fork上搜不到
希望上传 再次感谢

**Comment by kkHAIKE** [comment]
依赖库有cdn限制，好像staticfile可以随便添加，但是也好麻烦，那个jsbn不知道怎么合并好

**Comment by 432539** [comment]
作者你好,我想订制一款登陆获取COOKIE的可以吗?大约多少钱? 我Q432539,求回复
