### ISSUE TITLE
20220930下午左右 F115D失效，下载提示：很抱歉，提取码不能为空

### ISSUE THREAD

**Issue by icedrain0611** [kkHAIKE/fake115#101]

**Comment by ehwee** [comment]
+1

**Comment by billowcbt** [comment]
+1

**Comment by ltove** [comment]
+1

**Comment by freedoom2020** [comment]
same issue

**Comment by Landius** [comment]
有个扩展作者修复了，貌似115改了下加密
https://github.com/acgotaku/115/commit/12eb62170f2b2e9ee99db7253741fec755312d58#diff-64b8d9a552ac1ddcbf19bcf207260f85c56b6e3a6291d664ad02b55ee08e2712

**Comment by ww9592447** [comment]
我這邊根據大佬修復的代碼重新製作了 需要的拿去吧
https://github.com/ww9592447/fake115/blob/main/fake115d.user.js

**Comment by kkHAIKE** [comment]
直接提交pr吧 😊

**Comment by kkHAIKE** [comment]
relate https://github.com/kkHAIKE/fake115/pull/102
我看起来怎么像是只更新了 rsa key。。

**Comment by ww9592447** [comment]
> 相關#102 我看起來怎麼只是更新了 rsa key。。

就是因為變更的少 所以我才這麼快可以根據大佬的代碼來修改

**Comment by ehwee** [comment]
> 我這邊根據大佬修復的代碼重新製作了 需要的拿去吧 https://github.com/ww9592447/fake115/blob/main/fake115d.user.js

怎么下载不了了？

**Comment by fro1000** [comment]
請問更新後的1.03版本還是無法下載, 顯示"正在啟動115流覽器，請稍等", 然後会跳轉到 "你下載的檔大小超出限制，請使用最新115流覽器下載"的提示頁, 會是什麼原因呢?

**Comment by ww9592447** [comment]
> 之後的1.03無法請求下載，顯示“正在115流覽器，請啟動等”，然後會跳轉到“你下載的文件大小有限制”，請使用最新115流覽器下載的提示頁，會是什麼原因呢？

你的瀏覽器是什麼?
你是否還有其他的腳本影響到?
例如 舊版的 115转存助手ui优化版
我剛才意外發現 如果安裝這個會衝突到 狀況跟你一樣的

**Comment by fro1000** [comment]
有試過Chrome(106.0.5249.91正式版)和 Edge (105.0.1343.53正式版)都更新到最新版, 兩個瀏覽器都存在這個問題. 
Chrome有裝115轉存助手ui優化版, 刪除後問題仍然存在. 
Edge完全是乾淨的環境, 新裝的Tampermonkey和1.03腳本. 
不知道是否是因為我少裝了某個相关腳本

**Comment by ww9592447** [comment]
> 有試過Chrome(106.0.5249.91正式版)和Edge (105.0.1343.53正式版)都更新到最新版, 兩個瀏覽器都存在這個問題. Chrome有裝115轉存助手ui優化版, 刪除後問題仍然存在. Edge完全是乾淨的環境, 新裝的Tampermonkey和1.03腳本. 不知道是否是因為我少裝了某個相關腳本

你試試手動把腳本
'Content-Type': 'application/x-www-form-urlencoded'
這一行替換成這樣
'Content-Type': 'application/x-www-form-urlencoded',
'User-Agent': 'Mozilla/5.0;  Mac  OS  X/10.15.7;  115Desktop/2.0.1.7'
這樣還不行 那我也不知道什麼原因了

**Comment by icedrain0611** [comment]
Thanks for Update！
