### ISSUE TITLE
不正常登录统一收集

### ISSUE THREAD

**Issue by kkHAIKE** [kkHAIKE/fake115#14]
别新开issues了
最新提交可以输出一些调试信息，处理问题比较有帮助

**Comment by walexz** [comment]
正在登陆那转圈，
115浏览器状态
Array[2] "加载bridge-q"
Array[2] "加载bridge-q-成功 https://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1474284768847_0&_t1474284768847 : https://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1474284768847_0&_t1474284768847"
Array[3] "https://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1474284768847_0&_t1474284768847"
Uncaught TypeError: data.slice is not a function
["//msg.115.com/bridge_assets.html", "msg"] "加载bridge-msg"
["//msg.115.com/bridge_assets.html", "msg"] "加载bridge-msg-成功 https://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1474284788860_2&_t1474284788860 : https://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1474284788860_2&_t1474284788860"
["//msg.115.com/bridge_assets.html", "msg", "load"] "https://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1474284788860_2&_t1474284788860"

**Comment by chaizia** [comment]
firefox25.0.1+Scriptish 0.1.11.1-signed.1-signed
安装后依然是115浏览器提示- -#
[16:23:37.102] [fake115Browser@httpgithub.comkkHAIKEfake115] SyntaxError: illegal character @ file:///D:/soft/FF/profiles/scriptish_scripts/fake115browser@httpgithubcomkkhaikefake115/fake115browser@httpgithubcomkkhaikefake115.user.js:1
[16:23:37.801] 所用的 getPreventDefault() 已不赞成使用。请使用 defaultPrevented 替代。 @ http://assets.115.com/??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUtil/subscribe.min.js,commonFrame/urlMaintain.js,ajax/bridge.min.js,ajax/baseConnect.min.js?v=1474351882:3

**Comment by chaizia** [comment]
现在提示是[16:32:03.231] [fake115Browser@httpgithub.comkkHAIKEfake115] ReferenceError: cloneInto is not defined @ file:///D:/soft/FF/profiles/scriptish_scripts/fake115browser@httpgithubcomkkhaikefake115/fake115browser@httpgithubcomkkhaikefake115.user.js:261

[16:32:03.837] 所用的 getPreventDefault() 已不赞成使用。请使用 defaultPrevented 替代。 @ http://assets.115.com/??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUtil/subscribe.min.js,commonFrame/urlMaintain.js,ajax/bridge.min.js,ajax/baseConnect.min.js?v=1474351882:3

**Comment by jackiejtr** [comment]
15浏览器状态
assets.115.com/:4 Array[2] "加载bridge-qrcode"
assets.115.com/:4 Array[2] "加载bridge-q"
assets.115.com/:4 Array[2] "加载bridge-q-成功 http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1475070749838_1&_t1475070749838 : http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1475070749838_1&_t1475070749838"
assets.115.com/:4 Array[3] "http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1475070749838_1&_t1475070749838"
assets.115.com/:4 Array[2] "加载bridge-qrcode-成功 http://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1475070749315_0&_t1475070749316 : http://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1475070749315_0&_t1475070749316"
115.com/:10822 Uncaught TypeError: Cannot read property 'cookie' of undefined
assets.115.com/:4 Array[3] "http://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1475070749315_0&_t1475070749316"
assets.115.com/:4 Array[2] "加载bridge-msg"
assets.115.com/:4 Array[2] "加载bridge-msg-成功 http://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1475070775709_3&_t1475070775709 : http://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1475070775709_3&_t1475070775709"
assets.115.com/:4 Array[3] "http://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1475070775709_3&_t1475070775709" 无限转圈

**Comment by jackiejtr** [comment]
Array[2] "加载bridge-q"
assets.115.com/:4 Array[2] "加载bridge-q-成功 http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1475071036124_0&_t1475071036124 : http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1475071036124_0&_t1475071036124"
assets.115.com/:4 Array[3] "http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1475071036124_0&_t1475071036124"
VM405:10822 Uncaught TypeError: Cannot read property 'cookie' of undefined

**Comment by chenxuuu** [comment]
系统安全性升级，请下载最新版本！


event.js:1smartup started.
event.js:726end
event.js:718Object {config: Object, os: "win", devMode: false}
VM442:232url: 115.com/ storageName：ZzSVlleSAvMGJG rule: default
util-min.js?v=1477055615:1 115浏览器状态
event.js:1smartup started.
event.js:726end
event.js:1smartup started.
event.js:726end
event.js:1smartup started.
event.js:726end
event.js:1smartup started.
event.js:726end
event.js:1smartup started.
event.js:726end
event.js:1smartup started.
event.js:726end
event.js:1smartup started.
event.js:726end
event.js:718Object {config: Object, os: "win", devMode: false}
event.js:718Object {config: Object, os: "win", devMode: false}
event.js:718Object {config: Object, os: "win", devMode: false}
event.js:718Object {config: Object, os: "win", devMode: false}
event.js:718Object {config: Object, os: "win", devMode: false}
event.js:718Object {config: Object, os: "win", devMode: false}
event.js:718Object {config: Object, os: "win", devMode: false}
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 ["//q.115.com/bridge_assets.html", "q"] "加载bridge-q"
event.js:1smartup started.
event.js:726end
event.js:718Object {config: Object, os: "win", devMode: false}
event.js:1smartup started.
event.js:726end
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4["//q.115.com/bridge_assets.html", "q"]0: "//q.115.com/bridge_assets.html"1: "q"length: 2__proto__: Array[0] "加载bridge-q-成功 http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1477218919067_0&_t1477218919067 : http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1477218919067_0&_t1477218919067"
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 ["//q.115.com/bridge_assets.html", "q", "load"] "http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1477218919067_0&_t1477218919067"
event.js:718Object {config: Object, os: "win", devMode: false}
VM890:232url: q.115.com/bridge_assets.html storageName：olEixgmocctzNhEZBM rule: default
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 ["//qrcodeapi.115.com/bridge_assets.html", "qrcode"] "加载bridge-qrcode"
event.js:1smartup started.
event.js:726end
event.js:718Object {config: Object, os: "win", devMode: false}
event.js:1smartup started.
event.js:726end
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 ["//qrcodeapi.115.com/bridge_assets.html", "qrcode"] "加载bridge-qrcode-成功 http://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1477218928611_1&_t1477218928611 : http://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1477218928611_1&_t1477218928611"
event.js:718Object {config: Object, os: "win", devMode: false}
VM1014:232url: qrcodeapi.115.com/bridge_assets.html storageName：jciqUvleECkJHdbmkM rule: default
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 ["//qrcodeapi.115.com/bridge_assets.html", "qrcode", "load"] "http://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1477218928611_1&_t1477218928611"
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 ["//msg.115.com/bridge_assets.html", "msg"] "加载bridge-msg"
event.js:1smartup started.
event.js:726end
event.js:718Object {config: Object, os: "win", devMode: false}
event.js:1 smartup started.
event.js:726 end
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 ["//msg.115.com/bridge_assets.html", "msg"] "加载bridge-msg-成功 http://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1477218936184_3&_t1477218936184 : http://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1477218936184_3&_t1477218936184"
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 ["//msg.115.com/bridge_assets.html", "msg", "load"] "http://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1477218936184_3&_t1477218936184"
event.js:718 Object {config: Object, os: "win", devMode: false}config: ObjectdevMode: falseos: "win"__proto__: Object
VM1204:232 url: msg.115.com/bridge_assets.html storageName：zBDtenaJEXuwuO rule: default

**Comment by kkHAIKE** [comment]
@chaizia  
> cloneInto is not defined
所用的油猴插件不支持cloneInto，建议使用大众插件
@jackiejtr 
> Uncaught TypeError: Cannot read property 'cookie' of undefined
猜测是你用的浏览器区分对待unsafeWindow的document和沙盒document了

**Comment by cnbetac** [comment]
http://pj.iaoso.com/lib/query?src=t6413&t=115%EF%BC%8C%E8%AE%A9%E4%BF%A1%E6%81%AF%E6%9B%B4%E6%9C%89%E5%BA%8F&r=
访问不能

**Comment by sh3rry** [comment]
无限转圈

**Comment by 3322964** [comment]
chromium42 直接安装最新版 控制台提示错误  
Uncaught ReferenceError: SecureRandom is not defined
(anonymous function) @ script.js:34(anonymous function) @ script.js:435(anonymous function) @ script.js:437

**Comment by moshouhot** [comment]
Chromium 53.0.2785.143 不能登录

**Comment by kkHAIKE** [comment]
@moshouhot 详细控制台错误

**Comment by sino1641** [comment]
无法出现登陆界面。提示使用115浏览器。
原因同@3322964 
VM499:8753pre-main prep time: 9 ms
VM499:3ERROR: Execution of script 'fake 115Browser' failed! SecureRandom is not defined
(anonymous) @ VM499:3
(anonymous) @ VM499:4
(anonymous) @ VM499:9381
(anonymous) @ VM272:2
C @ VM498:59
create @ VM498:67
u @ VM498:16
run @ VM498:16
(anonymous) @ VM498:68
(anonymous) @ VM498:68
(anonymous) @ VM498:68
TM_back @ VM498:69
(anonymous) @ VM498:69
(anonymous) @ VM272:2
exec_fn @ VM272:1
(anonymous) @ VM272:10
(anonymous) @ VM272:9
e @ content.js:6
send @ content.js:8
next @ content.js:13
(anonymous) @ content.js:25
(anonymous) @ content.js:23
sendResponseAndClearCallback @ VM255 extensions::messaging:347
messageListener @ VM255 extensions::messaging:379
target.(anonymous function) @ extensions::SafeBuiltins:19
EventImpl.dispatchToListener @ extensions::event_bindings:388
target.(anonymous function) @ extensions::SafeBuiltins:19
publicClassPrototype.(anonymous function) @ extensions::utils:151
EventImpl.dispatch_ @ extensions::event_bindings:372
EventImpl.dispatch @ extensions::event_bindings:394
target.(anonymous function) @ extensions::SafeBuiltins:19
publicClassPrototype.(anonymous function) @ extensions::utils:151
dispatchOnMessage @ VM255 extensions::messaging:320
VM499:3 ReferenceError: SecureRandom is not defined
    at eval (eval at C (eval at exec_fn (:1:108)), <anonymous>:8815:1)
    at Window.tms_f6e69032_c4d8_4fe4_af5a_bcd796763817 (eval at C (eval at exec_fn (:1:108)), <anonymous>:9379:3)
    at <anonymous>:2:297
    at eval (eval at C (eval at exec_fn (:1:108)), <anonymous>:3:1)
    at eval (eval at C (eval at exec_fn (:1:108)), <anonymous>:4:3)
    at Object.eval (eval at C (eval at exec_fn (:1:108)), <anonymous>:9381:6)
    at <anonymous>:2:297
    at C (eval at exec_fn (:1:108), <anonymous>:59:204)
    at Object.create (eval at exec_fn (:1:108), <anonymous>:67:282)
    at u (eval at exec_fn (:1:108), <anonymous>:16:88)

**Comment by kkHAIKE** [comment]
SecureRandom is not defined 看起来是没有载入一个脚本

**Comment by sino1641** [comment]
多次刷新后能成功进入。
具体是怎么回事😂

**Comment by kkHAIKE** [comment]
`SecureRandom is not defined`
应该是网络问题没有载入jsbn脚本
已替换成github上的elliptic库

**Comment by IsayIsee** [comment]
一直转圈无法登陆

pre-main prep time: 24 ms
115浏览器状态
["//q.115.com/bridge_assets.html", "q"] "加载bridge-q"
["//q.115.com/bridge_assets.html", "q"] "加载bridge-q-成功 http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1479343252767_0&_t1479343252768 : http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1479343252767_0&_t1479343252768"
["//q.115.com/bridge_assets.html", "q", "load"] "http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1479343252767_0&_t1479343252768"
["//msg.115.com/bridge_assets.html", "msg"] "加载bridge-msg"
["//msg.115.com/bridge_assets.html", "msg"] "加载bridge-msg-成功 http://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1479343269573_1&_t1479343269574 : http://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1479343269573_1&_t1479343269574"
["//msg.115.com/bridge_assets.html", "msg", "load"] "http://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1479343269573_1&_t1479343269574"
Uncaught TypeError: Cannot read property 'cookie' of undefined

**Comment by kkHAIKE** [comment]
'Cannot read property 'cookie' of undefined'
提供所用的浏览器和插件列表，这个非常奇怪document居然没有cookie成员，很大的程度是因为浏览器权限限制或者插件限制

**Comment by sh3rry** [comment]
@kkHAIKE
停用所有第三方插件，从chrome应用商店重新安装tampermonkey插件（重置该插件），并仅使用fake115脚本，故障报错依旧。
Google Chrome 54.0.2840.98   （newest stable version ）  on  macos 10.12
360安全浏览器 8.2.1.316     （newest beta version） on  windows10

**Comment by sh3rry** [comment]
@kkHAIKE
停用所有第三方插件，从chrome应用商店重新安装tampermonkey插件（重置该插件），并仅使用fake115脚本，故障报错依旧。
Google Chrome 54.0.2840.98   （newest stable version ）  on  macos 10.12
360安全浏览器 8.2.1.316     （newest beta version） on  windows10

**Comment by kkHAIKE** [comment]
手边没有macos 10.12系统
我本机win10刚刚新装 360安全浏览器 8.2.1.316，然后直接装tampermonkey添加脚本直接测试通过。
请检查后台是否有安全防护进程的可能

**Comment by sh3rry** [comment]
@kkHAIKE 已经解决
一直正在登录,无限转圈 报错 Cannot read property 'cookie' of undefined
原因是账号需要二次验证
目前解决办法是下载115浏览器并正常验证登陆一次即可。
![drfgi1 fr zs sgljvouww2](https://cloud.githubusercontent.com/assets/9400373/20375823/8ef6b366-acbc-11e6-8cfa-1651083ad51a.png)

**Comment by sh3rry** [comment]
@kkHAIKE  可能找到原因了 。我换了一个别的115账号，发现脚本登陆正常，于是怀疑是账号问题。我下载了115浏览器登陆测试，发现报错的账号需要二次验证（手机验证），如下图，验证手机号并登陆后，我本以为已经可以使用脚本了，但是脚本发现仍然报错，此时，我使用115浏览器注销并登陆多次，没有再弹出手机验证框。
![drfgi1 fr zs sgljvouww2](https://cloud.githubusercontent.com/assets/9400373/20375992/07ac3b36-acbe-11e6-9f13-5bf0c5a73dac.png)

**Comment by sh3rry** [comment]
@kkHAIKE 目前猜测是 ，服务器根据浏览器信息 ，认为仍需要验证手机才能登陆，所以脚本报错。
解决方法 ：1.是否能测试是识别了哪些信息，然后伪造这些信息，使账号在115浏览器下手机验证一次便可正常使用脚本    2.使脚本正常显示验证框，可用的复现方法是，安全设置中始终开启两步验证，如下图。
![a75 azza61my7fow7gyjtuy](https://cloud.githubusercontent.com/assets/9400373/20376186/77ff8266-acbf-11e6-9223-cc24dc0d6870.png)

**Comment by kkHAIKE** [comment]
@sh3rry good job

**Comment by sh3rry** [comment]
验证窗口成功弹出，但输入正确验证码验证不通过，提示页面已过期，请重新登录，多次刷新重新登录获取验证码，错误依旧。
![pxyn5 f3r2a 0f 8peopm c](https://cloud.githubusercontent.com/assets/9400373/20380532/a03e67a6-acdd-11e6-9e63-251b8f6db76b.png)

**Comment by sh3rry** [comment]
@kkHAIKE  验证窗口成功弹出，但输入正确验证码验证不通过，提示页面已过期，请重新登录，多次刷新重新登录获取验证码，错误依旧。
![pxyn5 f3r2a 0f 8peopm c](https://cloud.githubusercontent.com/assets/9400373/20380559/c834a27a-acdd-11e6-9448-64de7ac7f321.png)

**Comment by kkHAIKE** [comment]
@sh3rry 希望你在317行之前，加入`GM_log(JSON.stringify(json));`
然后私信我控制台输出结果

**Comment by sh3rry** [comment]
@kkHAIKE 额，，怎么私信

**Comment by kkHAIKE** [comment]
才发现没公开邮件
@sh3rry  已经发你邮件。

**Comment by sh3rry** [comment]
@kkHAIKE ok

**Comment by IsayIsee** [comment]
@kkHAIKE 确实是二次认证的问题，现在已经可以登陆了，终于不用安装115浏览器了

**Comment by popokcn** [comment]
控制台报错：Uncaught TypeError: data.slice is not a function
登陆按钮无限转圈。

**Comment by kkHAIKE** [comment]
@popokcn 您的浏览器版本

**Comment by popokcn** [comment]
@kkHAIKE 七星浏览器，内核是 Chromium  43.0.2357.132

**Comment by popokcn** [comment]
![image](https://cloud.githubusercontent.com/assets/17810922/20866019/f3b0426a-ba5c-11e6-85b4-918c543919b7.png)
![image](https://cloud.githubusercontent.com/assets/17810922/20866025/1d966c4e-ba5d-11e6-99bb-39f6b3bc98e7.png)
为什么代码会有这么多错误提示？

**Comment by kkHAIKE** [comment]
@popokcn 你点击下VM421:10886，倒数第四行那种，跟踪进去截图看看

**Comment by popokcn** [comment]
@kkHAIKE 
![image](https://cloud.githubusercontent.com/assets/17810922/20866136/f2521dfa-ba5f-11e6-9b9e-e8d853733f0e.png)
![image](https://cloud.githubusercontent.com/assets/17810922/20866137/fe73c246-ba5f-11e6-8449-97b431d53368.png)

**Comment by kkHAIKE** [comment]
@popokcn 看起来不像是最新的，使用最新的试试

**Comment by popokcn** [comment]
@kkHAIKE 你的脚本吗？还是我的浏览器

**Comment by kkHAIKE** [comment]
@popokcn 脚本

**Comment by popokcn** [comment]
@kkHAIKE 脚本不是自动更新的吗？我重新装了下，果然可以了，你是不是改了脚本，没改版本号？导致没自动更新？

**Comment by kkHAIKE** [comment]
@popokcn 好像没弄自动更新

**Comment by popokcn** [comment]
@kkHAIKE 666，终于搞定网页登陆啦，不用再每次都拿出手机扫码啦。大神牛逼。

**Comment by kid2323** [comment]
請問到底要裝哪個腳本 fake115.coffee // fake115.user.js// fec115.js// fec115.min.js
為什麼我裝了之後 帳號密碼框 都沒出來
但我用代碼卻有出現 不過提交登錄 卻一直無限回圈

**Comment by kkHAIKE** [comment]
@kid2323 fake115.user.js，请提供控制台输出

**Comment by kid2323** [comment]
是這個嗎
http://imageon.org/img-5847b7ca76b79.html
上面還有一條 錯誤  ERROR: Execution of script 'fake 115Browser' failed! require is not defined

**Comment by kkHAIKE** [comment]
@kid2323 您是用什么插件载入脚本的。。。

**Comment by kid2323** [comment]
tampermonkey  難道版本有差
http://www.dumpt.com/img/viewer.php?file=mvw09gmvi8qt1a0mzuzx.jpg

**Comment by R-L-T-Y** [comment]
VM200:439 Uncaught ReferenceError: $ is not defined
    at Object.set_down_url (<anonymous>:439:17)
    at Object.init (<anonymous>:152:22)
    at <anonymous>:519:13
    at <anonymous>:520:11

17.01.06 无法正常登陆

**Comment by sino1641** [comment]
现在登录需要手机验证码了。
之前有一个版本是能跳过的。

**Comment by PromiseNev** [comment]
失效了,貌似115升级了,现在点账户登录不行了,不出现登录框.

**Comment by ZiPenOk** [comment]
失效了,115升级了,不出登录框,反复切换刷新后出现,但提示 系统安全性升级，请下载最新版本！

**Comment by chengs** [comment]
![screen shot 2017-02-14 at 2 15 45 pm](https://cloud.githubusercontent.com/assets/824529/22930371/2f483a30-f2c0-11e6-9425-a796bb48e703.png)

**Comment by kkHAIKE** [comment]
@chengs 已修复，aesjs更新了接口，返回不再是普通数组而是Uint8Array

**Comment by ZiPenOk** [comment]
现在可以扫码登录了,账号登陆还没修复吗 ? 我没出现登录框

**Comment by kkHAIKE** [comment]
账户密码登陆框要点击下面的‘使用帐号登录'，如果你没有这个的话可能脚本导入出问题了

**Comment by R-L-T-Y** [comment]
@kkHAIKE  还是需要手机验证码啊

**Comment by qq57240** [comment]
@kkHAIKE 又不行了，现在又需要下载115浏览器或扫码

**Comment by sino1641** [comment]
@R-L-T-Y 验证码这个无解，收不到验证码只有经常尝试登录等115记住这个ip
@kkHAIKE 换个地方更新吧，至少这个repo是被盯上了233

**Comment by kkHAIKE** [comment]
@qq57240 又封了一个机器名，再给点盗版系统名字

**Comment by qq57240** [comment]
@kkHAIKE 
老大，我用的是win10正版，360安全浏览器最新测试版

**Comment by kkHAIKE** [comment]
@qq57240 我内部虚拟的

**Comment by qq57240** [comment]
@kkHAIKE 
辛苦了，看来是被115盯上了！
要不建个QQ群，在群里更新

**Comment by qq57240** [comment]
可以了，但输入密码后现在要手机短信验证了，这个115真是。。。

**Comment by sino1641** [comment]
@qq57240 在不常用地点或者设备都要短信验证码。收个验证码也不是什么难事吧

**Comment by kid2323** [comment]
使用帳號登陸點下去 沒出現 登錄框
Chrome版本 49.0.2623.112 m
Tampermonkey 4.2.7 
插件全關了 還是沒出現 但我用火狐卻有登錄框
我不管怎麼刷新 都會有這2條錯誤 
Font from origin 'http://assets.115.com' has been blocked from loading by Cross-Origin Resource Sharing policy: The 'Access-Control-Allow-Origin' header has a value 'http://my.115.com' that is not equal to the supplied origin. Origin 'http://115.com' is therefore not allowed access.
VM1151:3ERROR: Execution of script 'fake 115Browser' failed! require is not defined
我用的腳本是最新的 請問是哪裡出錯了 腳本改版前我試過也是這樣

**Comment by kkHAIKE** [comment]
@kid2323 看不出问题，尝试更新chrome到55

**Comment by zsx0731** [comment]
需要短信验证。求解决

**Comment by kkHAIKE** [comment]
@zsx0731 短信验证正常的因为换到了新的电脑（脚本内的虚拟硬件信息），多登陆几次就不会了

**Comment by ZiPenOk** [comment]
发短信验证界面,控制台无限循环下列信息,收不到短信
![qq 20170513133656](https://cloud.githubusercontent.com/assets/17003855/26022829/5ded6048-37e1-11e7-9cdf-f14f1a834b27.jpg)

**Comment by kkHAIKE** [comment]
@ZiPenOk 如果到了短信验证阶段，就不是此脚本的范围了

**Comment by ZiPenOk** [comment]
@kkHAIKE 解决了,取消HTTPS Everywhere 对115 强制HTTPS就好了

**Comment by fr0der1c** [comment]
Error running script: fake 115Browser
ReferenceError: cloneInto is not defined
cloneInto is not defined

Chrome/macOS

**Comment by PromiseNev** [comment]
![qq 20170728003507](https://user-images.githubusercontent.com/16667188/28681654-d13ba7f4-732c-11e7-8b4f-5342d88536e1.png)
脚本失效了 大大！

**Comment by sino1641** [comment]
尝试下刷新？

**Comment by PromiseNev** [comment]
@sino1641 谢谢大佬！ 刷新了几次 好了。

**Comment by zsx0731** [comment]
macOS 10.13 safari 11下 不出现用户名密码的登录框，刷新几次还是不出现 求解决。

**Comment by kkHAIKE** [comment]
@zsx0731 这里关掉了，发新帖，遵守新帖法则
