### ISSUE TITLE
去除上传限制的支持？

### ISSUE THREAD

**Issue by wsxy162** [kkHAIKE/fake115#18]
可以正常登录，但是进入网盘上传界面会有 200MB 的大小限制，如果使用 115 浏览器就没有这个限制，那这个上传限制是不是也可以破解？

**Comment by kkHAIKE** [comment]
转载请注明出处，登录后马上运行（点击上传文件之前）
`var fakeSizeLimitGetter = function () {
  return 2147483648;
};
if (Object.defineProperty) {
  Object.defineProperty(UPLOAD_CONFIG_H5, "size_limit", {
    get: fakeSizeLimitGetter
  });
} else if (Object.prototype.__defineGetter__) {
  UPLOAD_CONFIG_H5.__defineGetter__("size_limit", fakeSizeLimitGetter);
}`

**Comment by wsxy162** [comment]
可用，但是不支持“极速上传”，也许这个需要插件支持。谢谢。

**Comment by kkHAIKE** [comment]
极速上传是指秒传？

2016-11-04 18:03 GMT+08:00 Dingzhong Chen <notifications@github.com>:

**Comment by wsxy162** [comment]
嗯。

**Comment by wsxy162** [comment]
是的。

**Comment by wsxy162** [comment]
[115upload_v1.1.8_x64.tar.gz](https://github.com/kkHAIKE/fake115/files/571594/115upload_v1.1.8_x64.tar.gz)
[115upload_v1.1.8_x86.tar.gz](https://github.com/kkHAIKE/fake115/files/571593/115upload_v1.1.8_x86.tar.gz)
这两个是 linux 上最后一个版本的插件了，官方地址已经 404 了，从迅雷服务器上拉下来的。装上去也是显示需要安装“115 浏览器”，不能启用“极速上传”。不知道可否伪装浏览器使用旧插件来上传。

**Comment by kkHAIKE** [comment]
你说的极速上传不是秒传吧，秒传指的是已经有了该文件其他地方上传过，再次上传就不用再传直接成功

**Comment by wsxy162** [comment]
没看到“秒传”的字样，我觉得你说的秒传跟极速上传就是一样的东西。极速上传就是先计算文件校验值，普通上传就没有，直接上传。

2016-11-05 0:22 GMT+08:00 kkHAIKE <notifications@github.com>:

**Comment by wsxy162** [comment]
[http://help.115.com/web/43990.html?id=1413533889903](115 帮助中心)
从这里看，秒传是极速上传下的一个子功能，极速上传需要控件/插件。

**Comment by kkHAIKE** [comment]
的确，极速上传=秒传+（断点续传+稳定）

**Comment by wsxy162** [comment]
现在是这些插件 115 很久没有维护了，极速上传的功能难道只能在它的绑定浏览器上用？

**Comment by kkHAIKE** [comment]
光靠js最多只能实现秒传，不过也非常复杂

**Comment by wsxy162** [comment]
115 推广他家的浏览器不知道是布局什么，网盘客户端的不能实现跨平台支持，这就残废了很多。

**Comment by acgotaku** [comment]
@kkHAIKE 球问 如何实现 LoginEncrypt 函数 逆向官方115浏览器么？

**Comment by kkHAIKE** [comment]
@acgotaku 雪月秋水君，的确如此

**Comment by acgotaku** [comment]
厉害厉害 要是能写篇文章分享下就好了

我很好奇这个怎么实现的

On Nov 6, 2016 16:32, "kkHAIKE" <notifications@github.com> wrote:

@acgotaku <https://github.com/acgotaku> 雪月秋水君，的确如此

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kkHAIKE/fake115/issues/18#issuecomment-258667175>, or mute
the thread

**Comment by kkHAIKE** [comment]
油猴增加秒传的想法：

1. 油猴不知道能不能使用FileReader读取本地文件，Firefox的是不行，chrome没有尝试过。
2. 界面上要增加一个`<input type='file'>`没想好放在哪里，和应该怎么放

**Comment by kkHAIKE** [comment]
@acgotaku 囧，有个小技巧，怕公布了官方封杀就麻烦

**Comment by acgotaku** [comment]
@kkHAIKE 可以私密分享么？ 我邮箱是  acgotaku311 # gmail.com
