### ISSUE TITLE
貌似115又升级了

### ISSUE THREAD

**Issue by kice** [kkHAIKE/fake115#19]
RT。用的是1.2版本的脚本。

**Comment by kkHAIKE** [comment]
奇怪，我可以登录呀，你啥现象

**Comment by PromiseNev** [comment]
最新版本的无法登陆,一直卡在正在登陆,转圈圈.

**Comment by zhanglianbo35** [comment]
想放弃115了，下载速度就50kb

发自我的 iPhone 

**Comment by popokcn** [comment]
我也是无法登陆，一直转圈圈中，没用成功过，但是老是看你在更新，每次总以为又修复了

**Comment by zhanglianbo35** [comment]
如何解决下载速度只有50kb的问题？

发自我的 iPhone 

**Comment by popokcn** [comment]
我有VIP，下载还是很快的，不过我基本不下载，就在线看视频

2016-11-13 23:41 GMT+08:00 GetRighT <notifications@github.com>:

**Comment by kkHAIKE** [comment]
@popokcn @PromiseNev 请提供控制台输出
