### ISSUE TITLE
关于共享文件的想法

### ISSUE THREAD

**Issue by kkHAIKE** [kkHAIKE/fake115#20]
现在115还能通过pickcode参数获取文件吗？我看到下载文件里面会有pickcode这个码不知道在其他用户还能有效么。另外如果这个方法不行还能通过秒传方式共享文件。

**Comment by rixtox** [comment]
之前試過把pickcode下載鏈接給朋友確認了沒法用。
估計只能用秒傳分享。

**Comment by LannSoros** [comment]
通过秒传来分享？好像有点酷啊

**Comment by jasonleong** [comment]
`fileid=XX&filename=XX&filesize=XX&pickcode=这个吗&preid=XX&quickid=&target=XX&user_id=XX&userid=XX`
指的是上面地址的pickcode参数吗?  试过了没用.报
`statusmsg":"userid\/filesize\/target\/pickcode invalid"`

"秒传"方法需要读取文件块取得preid,这个应该可以.只是不能做到像之前的"转存"那么好,需要读取文件.
要是有什么方法可以直接转存的话(即A帐号文件瞬间转到B帐号),那就word哥厉害了. 👍

**Comment by sino1641** [comment]
目前还能通过手机模拟器模拟GPS再分享。
不知道什么时候就会失效。
~~如果作者需要的话这边可以试试抓包~~

**Comment by kkHAIKE** [comment]
@sino1641 现在只能通过手机版分享文件？

**Comment by sino1641** [comment]
@kkHAIKE 目前只能想到这个方法。
或者问问115的人？
