### ISSUE TITLE
脚本失效反馈

### ISSUE THREAD

**Issue by LYCX2015** [kkHAIKE/fake115#24]
作者您好，脚本失效了，登陆提示“系统安全性升级，请下载最新版本！”，盼您有空时修复一下，感谢您的付出。

**Comment by kkHAIKE** [comment]
妈卖批

**Comment by jasonleong** [comment]
是失效了.应该是115改了下代码.
最受不了115非要他浏览器登陆的奇葩做法了.
加油! @kkHAIKE

**Comment by Thessalhydra** [comment]
[https://web-capture.net/picture.php?pic_index=1&presentation_method=inline](url)

**Comment by Vizards** [comment]
被115的人盯上了23333

**Comment by catshitz** [comment]
被盯失效+1

**Comment by sino1641** [comment]
@hegzh 被盯上了如何是好

**Comment by IsoaSFlus** [comment]
哭，失效了QAQ

**Comment by chengs** [comment]
这次似乎不是那么好修复的

**Comment by MrLonely7** [comment]
这如何是好

**Comment by ccloli** [comment]
看了下代码变更，原来只是模拟的 MAC 地址被拉黑了么……难怪版本比作者填写的版本号略小的 115 浏览器还能登录，作者辛苦了（
另外再劳烦作者更新下 @version 吧，否则刷不到更新（
