### ISSUE TITLE
想请教一下破解115内置API和验证算法用到的技术

### ISSUE THREAD

**Issue by Cozak** [kkHAIKE/fake115#25]
大触您好，俺通过分析115登陆界面的代码后也摸到了browserInterface.LoginEncryt，然而这接口貌似是115浏览器内置API（在firefox下未定义，在115浏览器console下显示为native code），因此停滞不前

今天有幸Google到您这神奇的脚本，仔细看过一遍发现115登陆验证竟如此复杂（各种加密+二次校验），因此很好奇您是如何分析得出的（抓包分析？还是逆向115浏览器？），想知道需要用到哪些技术、工具等相关知识，不知可否点拨一二给个方向？谢谢

**Comment by kkHAIKE** [comment]
分析：抓包(wireshark) + 逆向(ida)
语言：js(前期界面分析，后期测试/插件代码编写，chrome调试，我用coffee)
          c++(fec算法测试/模块代码编写)
          emscripten(转换c++到js)
算法：fec(本是ec算法，这里当作加密使用)，ecdh(密钥交换)，aes(加密)，lz4(压缩)，md4，md5，crc32(hash)

**Comment by Cozak** [comment]
大赞，谢谢啦
