### ISSUE TITLE
115更新导致排版错误

### ISSUE THREAD

**Issue by catshitz** [kkHAIKE/fake115#28]
![image](https://cloud.githubusercontent.com/assets/18102209/24582167/8bed9666-175c-11e7-8ce5-7361d35f7c58.png)

**Comment by ZiPenOk** [comment]
我也正想来反映这个问题,求更新

**Comment by sino1641** [comment]
顺便建议把默认显示的发现栏目换成115。。
开始搞社交的网盘真可怕

**Comment by kkHAIKE** [comment]
已提交
@sino1641 这个不会
