### ISSUE TITLE
Safari上无法正常进行登陆

### ISSUE THREAD

**Issue by 4553733** [kkHAIKE/fake115#29]
在Safari上安装了Tampermonkey然后安装了脚本，发现工作不太正常，具体表现为有时会显示二维码刷新一下后才会显示出[账号登陆]，**接着输入账号密码点击登陆后会有个进度圈一直在转然后卡着，无法跳转到个人页面。**

**Comment by kkHAIKE** [comment]
Safari 的版本和 Tampermonkey 的版本，操作系统版本

**Comment by 4553733** [comment]
macOS 10.12.4, Safari 10.1(12603.1.30.0.34), Tampermonkey 4.3

**Comment by kkHAIKE** [comment]
在Tampermonkey的沙盒里面缺少 ArrayBuffer.isView方法，我提了issus
https://github.com/Tampermonkey/tampermonkey/issues/379
实在需要的话我可以试试把unsafeWindow的重定向过来

**Comment by kkHAIKE** [comment]
官方issus升级了，试试看

**Comment by zsx0731** [comment]
kkHAIKE您好，我想问下 我每一次这个如果是重新登陆一次 打开浏览器第一个看到的是 115浏览器下载 然后刷新一次就好了。

**Comment by 4553733** [comment]
好，谢谢你。
kkHAIKE <notifications@github.com>于2017年4月22日 周六下午1:06写道：
