### ISSUE TITLE
2017.5.8 115网盘账号登陆脚本失效

### ISSUE THREAD

**Issue by zsx0731** [kkHAIKE/fake115#33]
提示安全系统升级。等待作者更新脚本

**Comment by zsx0731** [comment]
系统安全性升级，请下载新版本了，求作者更新脚本~

**Comment by catshitz** [comment]
系统安全性升级，请下载最新版本！+1
![image](https://cloud.githubusercontent.com/assets/18102209/25852354/a984f11c-34fb-11e7-8f66-b6aec8235d8c.png)
又被盯上了
![image](https://cloud.githubusercontent.com/assets/18102209/25852368/b59c77ea-34fb-11e7-885e-aafed3597253.png)
