### ISSUE TITLE
短消息驗證碼無法通過

### ISSUE THREAD

**Issue by jkgtw** [kkHAIKE/fake115#39]
環境是macOS 10.12.6
使用Safari安裝Tampermonkey

可以正常輸入帳號跟密碼，但是因為人不在國內
系統每次都要讓我SMS驗證，短消息我能收到
不過卻提示頁面過期？
<img width="972" alt="jietu20170817-185909" src="https://user-images.githubusercontent.com/1110347/29409456-db4fbe9e-837e-11e7-9e91-411cb7d90992.png">

**Comment by kkHAIKE** [comment]
1. 首先看看原版115是否能正常登录
2. 可以试试关闭二次验证

**Comment by jkgtw** [comment]
原版可以登入，使用的是iOS App來掃碼登入
我沒有打開115二次驗證的功能

**Comment by hqman** [comment]
抱歉 请问 在 mac 10.12.5  chrome 或者 safari 能运行吗? @jkgtw

**Comment by jkgtw** [comment]
10.12.6的Safari短消息驗證無法通過（會顯示頁面過期）

剛剛測試Chrome 60.0.3112.101(64 bit)可以正常運行
也會出現短消息驗證，但是可以通過

**Comment by hqman** [comment]
![d00f39d6-d0c7-4ad2-abbc-9ff6d504c996](https://user-images.githubusercontent.com/185824/29486550-50bcd552-851b-11e7-9a57-fa3da1505be9.png)

试了一下chrome 好像不起作用，有办法调试吗

**Comment by kkHAIKE** [comment]
看看控制台的输出

**Comment by kkHAIKE** [comment]
Safari 我晚上去试下，之前有人测试通过了的

**Comment by kkHAIKE** [comment]
Safari /Tampermonkey 版本号
