### ISSUE TITLE
最近是不是不行了？登录卡菊花了

### ISSUE THREAD

**Issue by asdfvv** [kkHAIKE/fake115#40]
一周没上，昨天要上115就卡菊花了

**Comment by kkHAIKE** [comment]
我刚才试了下正常，issue 请说明浏览器和操作系统

**Comment by asdfvv** [comment]
win10 firefox 56.0b4  难道是firefox的原因？

**Comment by asdfvv** [comment]
控制台有一条
所用的 getPreventDefault() 已不赞成使用。请改用 defaultPrevented。

**Comment by kkHAIKE** [comment]
试试新提交

**Comment by asdfvv** [comment]
用了新的脚本，现在连登录界面都显示不了了。

**Comment by asdfvv** [comment]
控制台
指向“chrome://light_plugin_f6f079488b53499db99380a7e11a93f6_kaspersky_com/content/script_plugins_detector.js”的 <script> 加载失败。  www.115.com:1
所用的 Mutation Events 已不赞成使用。请改用 MutationObserver。  %20line%202%20%3E%20eval:351:4
Array [ "//qrcodeapi.115.com/bridge_assets.h…", "qrcode" ] 加载bridge-qrcode  assets.115.com:4:32376
Array [ "//qrcodeapi.115.com/bridge_assets.h…", "qrcode" ] "加载bridge-qrcode-成功 https://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1503496084280_0&_t1503496084280 : https://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1503496084280_0&_t1503496084280"  assets.115.com:4:32376
Array [ "//qrcodeapi.115.com/bridge_assets.h…", "qrcode", "load" ] "https://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1503496084280_0&_t1503496084280"  assets.115.com:4:32376
所用的 Mutation Events 已不赞成使用。请改用 MutationObserver。  bridge_assets.html:351:4
所用的 getPreventDefault() 已不赞成使用。请改用 defaultPrevented。

**Comment by kkHAIKE** [comment]
我这边一切正常，firefox 版本和系统都和你一致
GM_log 的输出请在 ctrl+shit+J 里查看
![default](https://user-images.githubusercontent.com/64772/29647157-56cb5124-88ba-11e7-9652-c933004cf5d7.PNG)

**Comment by asdfvv** [comment]
登录界面有了，就是卡菊花？难得是网络问题？
我在试试
