### ISSUE TITLE
firefox 53.0.3  tampermonkey 扩展，不知何故无效

### ISSUE THREAD

**Issue by Hypnus051** [kkHAIKE/fake115#41]
如题，不是IT专业人士，烦请指点。

**Comment by kkHAIKE** [comment]
用 firefox 查看 GM_log，需要使用 Ctrl+Shift+J

**Comment by Hypnus051** [comment]
嗯，很多很长的应该是错误log，需要另存一下传上来吗？

**Comment by kkHAIKE** [comment]
发上来呗。。。

**Comment by Hypnus051** [comment]
没找到导出，就直接copy了日志。。。。
——————————————————————————————————————————————
undefined  Promise-backend.js:920
2017-09-04T02:51:46.201Z: Starting adguard... Version: 2.6.7. Id: adguardadblocker@adguard.com  log.js:71:9
2017-09-04T02:51:46.264Z: Filters metadata loaded  log.js:71:9
2017-09-04T02:51:46.337Z: Filters i18n metadata loaded  log.js:71:9
2017-09-04T02:51:46.363Z: Starting loading filter rules from the storage  log.js:71:9
2017-09-04T02:51:46.580Z: Finished loading filter rules from the storage in 217 ms  log.js:71:9
2017-09-04T02:51:46.581Z: Starting request filter initialization. Async=false  log.js:71:9
2017-09-04T02:51:47.229Z: Finished request filter initialization in 647 ms. Rules count: 83462  log.js:71:9
Storage: use chromeStorage  storage.js:19:501
statistics: Unable to load GA -> enable emergency mode  statistics.js:3:508
Storage: test -> start  storage.js:11:59
PushService:stateChangeProcessEnqueue: Error transitioning state UnknownError  PushService.jsm:160
Storage: test -> set after 2911ms  storage.js:11:151
Storage: test -> get after 2952ms  storage.js:11:256
Storage: test -> remove after 3474ms  storage.js:12:96
SDK worker-child started as frozen on unexpected initial document.readyState Object { initialDocumentReadyState: "uninitialized", windowLocation: "about:blank" }  worker-child.js:62
SDK worker-child started as frozen on unexpected initial document.readyState Object { initialDocumentReadyState: "uninitialized", windowLocation: "about:blank" }  worker-child.js:62
fdm_extension:input format error  core.js:106
SDK worker-child started as frozen on unexpected initial document.readyState Object { initialDocumentReadyState: "uninitialized", windowLocation: "about:addons" }  worker-child.js:62
[flv.js] > Playback seems stuck at 0, seek to 0.082  bilibiliPlayer.min.js:1848:3373
[10:56:26]   下一次重试：0ms后  connworker.js:1:4362
2017-09-04T02:56:46.575Z: Start checking filters updates  log.js:71:9
2017-09-04T02:56:46.576Z: Checking updates for 2 filters  log.js:71:9
[10:56:54]  Object { code: 0, data: Object, state: 1 }  connworker.js:1:3023
[10:56:54]  Object { code: 0, data: Object, state: 1 }  connworker.js:1:3023
[10:56:54]   下一次重试：0ms后  connworker.js:1:4362
[10:56:56]   主动断开重连 undefined  connworker.js:1:2347
[10:56:56]   下一次重试：1000ms后  connworker.js:1:4362
Error: Permission denied to access property "Element"
堆栈跟踪：
isGlobalProperty@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://support-at-lastpass-dot-com/data/onloadwff.js:13:18
get@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://support-at-lastpass-dot-com/data/onloadwff.js:25:54
u@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://support-at-lastpass-dot-com/data/onloadwff.js:79:1240
g@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://support-at-lastpass-dot-com/data/onloadwff.js:79:2090
onEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://gre/modules/commonjs/sdk/content/content-worker.js:45:22
onEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://gre/modules/commonjs/sdk/content/content-worker.js:45:22
onChromeEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://gre/modules/commonjs/sdk/content/content-worker.js:91:16
  timers.js:43
[10:56:57]   下一次重试：3000ms后  connworker.js:1:4362
Array [ "//qrcodeapi.115.com/bridge_assets.h…", "qrcode" ] 加载bridge-qrcode  assets.115.com:4:32376
Array [ "//qrcodeapi.115.com/bridge_assets.h…", "qrcode" ] "加载bridge-qrcode-成功 http://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1504493818273_0&_t1504493818273 : http://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1504493818273_0&_t1504493818273"  assets.115.com:4:32376
Array [ "//qrcodeapi.115.com/bridge_assets.h…", "qrcode", "load" ] "http://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1504493818273_0&_t1504493818273"  assets.115.com:4:32376
undefined  Promise-backend.js:920

**Comment by kkHAIKE** [comment]
看起来像是你的 lastpass 问题

2017-09-04 10:59 GMT+08:00 Hypnus051 <notifications@github.com>:

**Comment by Hypnus051** [comment]
禁用了一下lastpass， 也没改善。。。

**Comment by kkHAIKE** [comment]
1. 您先尝试禁用所有其他插件
2. 替换成 greasemonkey 脚本插件

**Comment by Hypnus051** [comment]
今天火狐疯狂后台强制更新，一更新就卡死，我已经关了所有的自动更新都没用。。。等我先解决这个问题，再来试一下。另外以前一直是用greasemonkey的，但是fake115也一直无效，管理脚本又不如tampermonkey于是就换了，edge上装了tampermonkey和lastpass倒是可以用

**Comment by Hypnus051** [comment]
firefox回滚53.0版本并整个翻新之后，导入febe备份，目前可以使用了
