### ISSUE TITLE
Chrome 60.0.3112.113 下失效，版本1.3.4

### ISSUE THREAD

**Issue by GitZj** [kkHAIKE/fake115#42]
ERROR: Execution of script 'fake 115Browser' failed! require is not defined
(anonymous) @ :sourcemap:3

**Comment by kkHAIKE** [comment]
你用的tampermonkey插件吗

**Comment by GitZj** [comment]
是的

**Comment by kkHAIKE** [comment]
贴上控制台日志，我和你一样环境是正常的

**Comment by GitZj** [comment]
求教控制台日志怎么贴？F12复制全部吗？

**Comment by kkHAIKE** [comment]
可以

**Comment by GitZj** [comment]
:sourcemap:8 Tampermonkey: couldn't load @require from URL https://rawgit.com/ricmoo/aes-js/master/index.js
tms_4ec957dd_515f_498b_80b4_d97f8af23533 @ :sourcemap:8
:sourcemap:10 Tampermonkey: couldn't load @require from URL https://rawgit.com/kkHAIKE/node-lz4/balabala/build/lz4.min.js
tms_4ec957dd_515f_498b_80b4_d97f8af23533 @ :sourcemap:10
:sourcemap:12 Tampermonkey: couldn't load @require from URL https://rawgit.com/indutny/elliptic/master/dist/elliptic.min.js
tms_4ec957dd_515f_498b_80b4_d97f8af23533 @ :sourcemap:12
:sourcemap:14 Tampermonkey: couldn't load @require from URL https://rawgit.com/emn178/js-md4/master/build/md4.min.js
tms_4ec957dd_515f_498b_80b4_d97f8af23533 @ :sourcemap:14
:sourcemap:16 Tampermonkey: couldn't load @require from URL https://rawgit.com/kkHAIKE/fake115/master/fec115.min.js
tms_4ec957dd_515f_498b_80b4_d97f8af23533 @ :sourcemap:16
:sourcemap:44 Tampermonkey: couldn't load @require from URL https://rawgit.com/pierrec/js-xxhash/master/build/xxhash.min.js
tms_4ec957dd_515f_498b_80b4_d97f8af23533 @ :sourcemap:44
:sourcemap:3 ERROR: Execution of script 'fake 115Browser' failed! require is not defined
(anonymous) @ :sourcemap:3
:sourcemap:3 ReferenceError: require is not defined
    at eval (eval at E_c (:3:221), <anonymous>:77:1)
    at Window.tms_4ec957dd_515f_498b_80b4_d97f8af23533 (eval at E_c (:3:221), <anonymous>:608:3)
    at <anonymous>:2:398
    at eval (eval at E_c (:3:221), <anonymous>:3:1)
    at eval (eval at E_c (:3:221), <anonymous>:4:3)
    at Object.eval (eval at E_c (:3:221), <anonymous>:610:6)
    at <anonymous>:2:398
    at Object.E_c (<anonymous>:3:219)
    at E (eval at exec_fn (:1:108), <anonymous>:58:467)
    at Object.create (eval at exec_fn (:1:108), <anonymous>:67:51)
assets.115.com/:4 Array(2)0: "//qrcodeapi.115.com/bridge_assets.html"1: "qrcode"length: 2__proto__: Array(0) "加载bridge-qrcode"
assets.115.com/:4 Array(2)0: "//qrcodeapi.115.com/bridge_assets.html"1: "qrcode"length: 2__proto__: Array(0)concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Object "加载bridge-qrcode-成功 http://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1504507132183_0&_t1504507132183 : http://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1504507132183_0&_t1504507132183"
assets.115.com/:4 Array(3) "http://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1504507132183_0&_t1504507132183"

**Comment by kkHAIKE** [comment]
你的 dns 解析不了 rawgit.com

**Comment by GitZj** [comment]
强制启用代理后可以使用了，谢谢
