### ISSUE TITLE
115不能使用账号密码登陆

### ISSUE THREAD

**Issue by googooog** [kkHAIKE/fake115#46]
### 我的控制台日志如下 (firefox 用户请拷贝 Ctrl+Shift+J 界面中的内容)

:sourcemap:835 pre-main prep time: 18 ms

**Comment by kkHAIKE** [comment]
chrome 版本是什么，你有截图吗

**Comment by googooog** [comment]
<img src=http://chuantu.biz/t6/54/1505740412x2079679416.png />
<img src=http://chuantu.biz/t6/54/1505740476x2890173897.png />

**Comment by kkHAIKE** [comment]
我环境和你一样，能贴出你控制台图片吗

**Comment by googooog** [comment]
<img src=http://chuantu.biz/t6/54/1505740929x2890173897.png />

**Comment by kkHAIKE** [comment]
你点过那个使用帐号登录的按钮吗

**Comment by googooog** [comment]
点了,还是提示这个,然后连续切换二维码登陆和账号登陆就出现用账号登陆了……
是我的网速慢么?

**Comment by kkHAIKE** [comment]
有可能访问 rawgit.com 太慢导致下不了js，chrome 就会这样

**Comment by googooog** [comment]
每次都得刷新几次才能出账号密码登陆

**Comment by googooog** [comment]
哦,谢谢,可能是我的vps网速慢哈,再次感谢
