### ISSUE TITLE
115网盘用户密码的登陆框无法出现。

### ISSUE THREAD

**Issue by zsx0731** [kkHAIKE/fake115#47]
我的操作系统是，版本是macOS 10.13
我的浏览器是，版本是Safari 11
用户密码的登陆框无法出现。
我能访问/Ping通 rawgit.com 
我是点击了主界面 "使用帐号登录"，重复刷新了几次，还是没有出现

**Comment by kkHAIKE** [comment]
请遵守发帖规范

**Comment by zsx0731** [comment]
真的无法出现登录框啊 求解决啊 kk大大

**Comment by kkHAIKE** [comment]
囧，你不遵守规范，我怎么答你啊。先自我排查一部分，然后再贴控制台记录呀。。

**Comment by zsx0731** [comment]
谢谢大大的支持
