### ISSUE TITLE
115打不开,关闭脚本可进

### ISSUE THREAD

**Issue by ZiPenOk** [kkHAIKE/fake115#49]
# 不遵守规范直接 close

### 我能否访问/Ping通 rawgit.com (最近地方 DNS 有屏蔽此域名)
是
### 我是否点击了主界面 "使用帐号登录"，重复刷新了几次
进不去首页
### 我的操作系统是，版本是
win10 企业版
### 我的浏览器是，版本是
chrome 60
### 我的控制台日志如下 (firefox 用户请拷贝 Ctrl+Shift+J 界面中的内容)
??oofUtil.js,libs/jquery-1.7.2.js,jquery-extend.js,oofUtil/date.js,oofUtil/template.js,oofUtil/subscribe.js,oofUtil/cookies.js,plug/copy/copy.js,ajax/bridge.js,ajax/fileUpload.js?v=2017062919:1 (2) ["//home.115.com/m_r/bridge_assets_628536c.html", "home"] "加载bridge-home"
:sourcemap:835 pre-main prep time: 2 ms
2VM610:2 A Parser-blocking, cross site (i.e. different eTLD+1) script, http://cdn.bootcss.com/jsSHA/2.2.0/sha1.js?tcdsp, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message.See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ VM610:2
c.(anonymous function) @ VM647:45
_add @ :sourcemap:836
(anonymous) @ :sourcemap:836
tms_1cd5018b_86f9_4739_b669_a3d37769fbdd @ :sourcemap:836
(anonymous) @ VM610:2
(anonymous) @ :sourcemap:3
(anonymous) @ :sourcemap:4
(anonymous) @ :sourcemap:1400
(anonymous) @ VM610:2
E_c @ VM610:3
ha @ VM647:61
create @ VM647:70
f @ VM647:15
run @ VM647:15
(anonymous) @ VM647:72
(anonymous) @ VM610:2
c @ VM610:2
(anonymous) @ VM647:72
(anonymous) @ VM647:72
TM_back @ VM647:73
(anonymous) @ VM647:73
(anonymous) @ VM610:2
exec_fn @ VM610:2
(anonymous) @ VM610:11
Y @ VM610:9
e @ content.js:6
send @ content.js:8
next @ content.js:13
(anonymous) @ content.js:28
(anonymous) @ content.js:24
sendResponseAndClearCallback @ VM586 extensions::messaging:366
messageListener @ VM586 extensions::messaging:398
EventImpl.dispatchToListener @ VM579 extensions::event_bindings:380
publicClassPrototype.(anonymous function) @ VM585 extensions::utils:149
EventImpl.dispatch_ @ VM579 extensions::event_bindings:364
EventImpl.dispatch @ VM579 extensions::event_bindings:386
publicClassPrototype.(anonymous function) @ VM585 extensions::utils:149
dispatchOnMessage @ VM586 extensions::messaging:339
DevTools failed to parse SourceMap: http://115.com/home/md5.min.js.map
(index):287 GET https://hm.baidu.com/hm.js?44a958b429c66ae50f8bf3a9d959ccf5 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ (index):287
(anonymous) @ (index):288
setTimeout (async)
(anonymous) @ (index):282
??oofUtil.js,libs/jquery-1.7.2.js,jquery-extend.js,oofUtil/date.js,oofUtil/template.js,oofUtil/subscribe.js,oofUtil/cookies.js,plug/copy/copy.js,ajax/bridge.js,ajax/fileUpload.js?v=2017062919:1 (2) ["iframe_cb_key__1505978902632_0", 1]
??oofUtil.js,libs/jquery-1.7.2.js,jquery-extend.js,oofUtil/date.js,oofUtil/template.js,oofUtil/subscribe.js,oofUtil/cookies.js,plug/copy/copy.js,ajax/bridge.js,ajax/fileUpload.js?v=2017062919:1 (2) ["//home.115.com/m_r/bridge_assets_628536c.html", "home"] "加载bridge-home"
??oofUtil.js,libs/jquery-1.7.2.js,jquery-extend.js,oofUtil/date.js,oofUtil/template.js,oofUtil/subscribe.js,oofUtil/cookies.js,plug/copy/copy.js,ajax/bridge.js,ajax/fileUpload.js?v=2017062919:1 (2) ["iframe_cb_key__1505978908015_1", 1]
??oofUtil.js,libs/jquery-1.7.2.js,jquery-extend.js,oofUtil/date.js,oofUtil/template.js,oofUtil/subscribe.js,oofUtil/cookies.js,plug/copy/copy.js,ajax/bridge.js,ajax/fileUpload.js?v=2017062919:1 (2) ["//home.115.com/m_r/bridge_assets_628536c.html", "home"] "加载bridge-home"
??oofUtil.js,libs/jquery-1.7.2.js,jquery-extend.js,oofUtil/date.js,oofUtil/template.js,oofUtil/subscribe.js,oofUtil/cookies.js,plug/copy/copy.js,ajax/bridge.js,ajax/fileUpload.js?v=2017062919:1 (2) ["iframe_cb_key__1505978913234_2", 1]
??oofUtil.js,libs/jquery-1.7.2.js,jquery-extend.js,oofUtil/date.js,oofUtil/template.js,oofUtil/subscribe.js,oofUtil/cookies.js,plug/copy/copy.js,ajax/bridge.js,ajax/fileUpload.js?v=2017062919:1 (2) ["//home.115.com/m_r/bridge_assets_628536c.html", "home"] "加载bridge-home"
### 我遇到了什么问题，截图
![2](https://user-images.githubusercontent.com/17003855/30683930-d32b8198-9ee1-11e7-8a89-217769e2c928.jpg)

关闭脚本即可进
![1](https://user-images.githubusercontent.com/17003855/30683954-dd410586-9ee1-11e7-8aa5-f9eab204ab43.jpg)

**Comment by kkHAIKE** [comment]
> 2VM610:2 A Parser-blocking, cross site (i.e. different eTLD+1) script, http://cdn.bootcss.com/jsSHA/2.2.0/sha1.js?tcdsp, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message.See https://www.chromestatus.com/feature/5718547946799104 for more details.

这个是错误，从提供的链接看你的网速非常慢？模拟了2G？chrome 会关掉跨站脚本，导致 sha1 脚本无法载入

**Comment by ZiPenOk** [comment]
网速慢 ? 不会啊,具体怎么回事不知道,反正关闭脚本是可进的,秒开网页啊

**Comment by kkHAIKE** [comment]
我更新了脚本，更换了所有的 bootcdn 的脚本链接为最新的，你再试试

**Comment by ZiPenOk** [comment]
还是不行

??oofUtil.js,libs/jquery-1.7.2.js,jquery-extend.js,oofUtil/date.js,oofUtil/template.js,oofUtil/subscribe.js,oofUtil/cookies.js,plug/copy/copy.js,ajax/bridge.js,ajax/fileUpload.js?v=2017062919:1 (2) ["//home.115.com/m_r/bridge_assets_628536c.html", "home"]0: "//home.115.com/m_r/bridge_assets_628536c.html"1: "home"length: 2__proto__: Array(0) "加载bridge-home"
:sourcemap:835 pre-main prep time: 1 ms
VM390:2 A Parser-blocking, cross site (i.e. different eTLD+1) script, http://cdn.bootcss.com/jsSHA/2.2.0/sha1.js?tcdsp, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message.See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ VM390:2
c.(anonymous function) @ VM424:45
_add @ :sourcemap:836
(anonymous) @ :sourcemap:836
tms_1cd5018b_86f9_4739_b669_a3d37769fbdd @ :sourcemap:836
(anonymous) @ VM390:2
(anonymous) @ :sourcemap:3
(anonymous) @ :sourcemap:4
(anonymous) @ :sourcemap:1400
(anonymous) @ VM390:2
E_c @ VM390:3
ha @ VM424:61
create @ VM424:70
f @ VM424:15
run @ VM424:15
(anonymous) @ VM424:72
(anonymous) @ VM390:2
c @ VM390:2
(anonymous) @ VM424:72
(anonymous) @ VM424:72
TM_back @ VM424:73
(anonymous) @ VM424:73
(anonymous) @ VM390:2
exec_fn @ VM390:2
(anonymous) @ VM390:11
Y @ VM390:9
e @ content.js:6
send @ content.js:8
next @ content.js:13
(anonymous) @ content.js:28
(anonymous) @ content.js:24
sendResponseAndClearCallback @ VM366 extensions::messaging:366
messageListener @ VM366 extensions::messaging:398
EventImpl.dispatchToListener @ VM359 extensions::event_bindings:380
publicClassPrototype.(anonymous function) @ VM365 extensions::utils:149
EventImpl.dispatch_ @ VM359 extensions::event_bindings:364
EventImpl.dispatch @ VM359 extensions::event_bindings:386
publicClassPrototype.(anonymous function) @ VM365 extensions::utils:149
dispatchOnMessage @ VM366 extensions::messaging:339
DevTools failed to parse SourceMap: http://115.com/home/md5.min.js.map
??oofUtil.js,libs/jquery-1.7.2.js,jquery-extend.js,oofUtil/date.js,oofUtil/template.js,oofUtil/subscribe.js,oofUtil/cookies.js,plug/copy/copy.js,ajax/bridge.js,ajax/fileUpload.js?v=2017062919:1 (2) ["iframe_cb_key__1506057136824_0", 1]
??oofUtil.js,libs/jquery-1.7.2.js,jquery-extend.js,oofUtil/date.js,oofUtil/template.js,oofUtil/subscribe.js,oofUtil/cookies.js,plug/copy/copy.js,ajax/bridge.js,ajax/fileUpload.js?v=2017062919:1 (2) ["//home.115.com/m_r/bridge_assets_628536c.html", "home"] "加载bridge-home"
??oofUtil.js,libs/jquery-1.7.2.js,jquery-extend.js,oofUtil/date.js,oofUtil/template.js,oofUtil/subscribe.js,oofUtil/cookies.js,plug/copy/copy.js,ajax/bridge.js,ajax/fileUpload.js?v=2017062919:1 (2) ["iframe_cb_key__1506057142241_1", 1]
??oofUtil.js,libs/jquery-1.7.2.js,jquery-extend.js,oofUtil/date.js,oofUtil/template.js,oofUtil/subscribe.js,oofUtil/cookies.js,plug/copy/copy.js,ajax/bridge.js,ajax/fileUpload.js?v=2017062919:1 (2) ["//home.115.com/m_r/bridge_assets_628536c.html", "home"] "加载bridge-home"
??oofUtil.js,libs/jquery-1.7.2.js,jquery-extend.js,oofUtil/date.js,oofUtil/template.js,oofUtil/subscribe.js,oofUtil/cookies.js,plug/copy/copy.js,ajax/bridge.js,ajax/fileUpload.js?v=2017062919:1 (2) ["iframe_cb_key__1506057147460_2", 1]
??oofUtil.js,libs/jquery-1.7.2.js,jquery-extend.js,oofUtil/date.js,oofUtil/template.js,oofUtil/subscribe.js,oofUtil/cookies.js,plug/copy/copy.js,ajax/bridge.js,ajax/fileUpload.js?v=2017062919:1 (2) ["//home.115.com/m_r/bridge_assets_628536c.html", "home"] "加载bridge-home"

**Comment by kkHAIKE** [comment]
看错误提示，你没有更新呀。。。还是 2.2.0 版本的 sha1，我已经更新到 2.3.1

**Comment by ZiPenOk** [comment]
我昨天是通过管理器更新的,还是出现这种情况,今天我直接从github重安装了一次,搞定了!现在好了
