### ISSUE TITLE
firefox48不正常，chrome 52正常

### ISSUE THREAD

**Issue by dsyo2008** [kkHAIKE/fake115#5]
firefox48上115登录无限。。。没反应
chrome 52无问题，登录成功进去！

firefox48日志：

> download:TypeError: this.contextMenuContentData is null
堆栈跟踪：
updateItemVisibilities@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/context-menu.js:1001:11
s3menuwizard.start_prepare@chrome://s3menuwizard/content/s3menuwizard.js:64:5
s3menuwizard.start@chrome://s3menuwizard/content/s3menuwizard.js:37:3
s3menuwizard.init/<@chrome://s3menuwizard/content/s3menuwizard.js:29:3
context-menu.js:1010
SDK worker-child started as frozen on unexpected initial document.readyState Object { initialDocumentReadyState: "uninitialized", windowLocation: "about:blank" }worker-child.js:62
【KF Online助手】加载完毕，加载耗时：10msKF_Online%25E5%258A%25A9%25E6%2589%258B.user.js:11615:9
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
Content Security Policy: 页面设置阻止读取位于 about:blank 的一项资源("base-uri https://github.com")。（未知）
所用的 Mutation Events 已不赞成使用。使用 MutationObserver 替代。360,%25E7%2599%25BE%25E5%25BA%25A6%25E7%25BD%2591%25E7%259B%2598,%25E5%25BE%25AE%25E7%259B%2598%25E9%2593%25BE%25E6%258E%25A5.user.js:35:16
getElementById() 被传递了空字符串参数。github-3f219d764b9f008c1a547073e539d9e1596110009d82b5f4c9639d9d5add3c5b.js:7:15340
getElementById() 被传递了空字符串参数。frameworks-ff9877ee49c73cb51e41545b924373427284ddceb2cd726e19ad79070a189212.js:9:5927
Content Security Policy: 页面设置阻止读取位于 self 的一项资源("script-src https://assets-cdn.github.com")。fake115:1
所用的 getPreventDefault() 已不赞成使用。请使用 defaultPrevented 替代。jquery-1.5.1.min.js:16:31260
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
TypeError: aElement.ownerDocument.location is nullvideoExtractorController.js:44:7
TypeError: can't access dead objectMouseover_Popup_Image_Viewer.user.js:504:1
TypeError: aElement.ownerDocument.location is nullvideoExtractorController.js:44:7
unreachable code after return statement[详细了解]util-min.js:1:35589
unreachable code after return statement[详细了解]core-min.js:1:1671
unreachable code after return statement[详细了解]core-min.js:1:30231
unreachable code after return statement[详细了解]core-min.js:1:92346
unreachable code after return statement[详细了解]core-min.js:1:95332
unreachable code after return statement[详细了解]core-min.js:1:102690
unreachable code after return statement[详细了解]core-min.js:1:170035
unreachable code after return statement[详细了解]core-min.js:1:176045
unreachable code after return statement[详细了解]core-min.js:1:179098
unreachable code after return statement[详细了解]assets.115.com:12:8
115浏览器状态util-min.js:1:36142
所用的 getPreventDefault() 已不赞成使用。请使用 defaultPrevented 替代。assets.115.com:3:7108
密码字段出现在一个不安全的 http:// 页面中。这是一个可能导致用户登录凭据被窃取的安全风险。[详细了解]115.com
密码字段出现在一个不安全的 http:// 表单动作中。这是一个可能导致用户登录凭据被窃取的安全风险。[详细了解]115.com
所用的 Mutation Events 已不赞成使用。使用 MutationObserver 替代。360,%25E7%2599%25BE%25E5%25BA%25A6%25E7%25BD%2591%25E7%259B%2598,%25E5%25BE%25AE%25E7%259B%2598%25E9%2593%25BE%25E6%258E%25A5.user.js:35:16
unreachable code after return statement[详细了解]core-min.js:1:95332
Array [ "//q.115.com/bridge_assets.html", "q" ] 加载bridge-qassets.115.com:4:41073
Array [ "//q.115.com/bridge_assets.html", "q" ] "加载bridge-q-成功 http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1471341744889_0&_t1471341744889 : http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1471341744889_0&_t1471341744889"assets.115.com:4:41073
所用的 Mutation Events 已不赞成使用。使用 MutationObserver 替代。360,%25E7%2599%25BE%25E5%25BA%25A6%25E7%25BD%2591%25E7%259B%2598,%25E5%25BE%25AE%25E7%259B%2598%25E9%2593%25BE%25E6%258E%25A5.user.js:35:16
Array [ "//q.115.com/bridge_assets.html", "q", "load" ] "http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1471341744889_0&_t1471341744889"assets.115.com:4:41073
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
所用的 Mutation Events 已不赞成使用。使用 MutationObserver 替代。360,%25E7%2599%25BE%25E5%25BA%25A6%25E7%25BD%2591%25E7%259B%2598,%25E5%25BE%25AE%25E7%259B%2598%25E9%2593%25BE%25E6%258E%25A5.user.js:35:16
Array [ "//passport.115.com/bridge_assets.ht…", "passport" ] 加载bridge-passportassets.115.com:4:41073
Array [ "//passport.115.com/bridge_assets.ht…", "passport" ] "加载bridge-passport-成功 http://passport.115.com/bridge_assets.html?cb_key=iframe_cb_key__1471341745745_1&_t1471341745745 : http://passport.115.com/bridge_assets.html?cb_key=iframe_cb_key__1471341745745_1&_t1471341745745"assets.115.com:4:41073
所用的 Mutation Events 已不赞成使用。使用 MutationObserver 替代。360,%25E7%2599%25BE%25E5%25BA%25A6%25E7%25BD%2591%25E7%259B%2598,%25E5%25BE%25AE%25E7%259B%2598%25E9%2593%25BE%25E6%258E%25A5.user.js:35:16
Array [ "//passport.115.com/bridge_assets.ht…", "passport", "load" ] "http://passport.115.com/bridge_assets.html?cb_key=iframe_cb_key__1471341745745_1&_t1471341745745"assets.115.com:4:41073
Array [ "//msg.115.com/bridge_assets.html", "msg" ] 加载bridge-msgassets.115.com:4:41073
Array [ "//msg.115.com/bridge_assets.html", "msg" ] "加载bridge-msg-成功 http://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1471341746240_2&_t1471341746240 : http://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1471341746240_2&_t1471341746240"assets.115.com:4:41073
所用的 Mutation Events 已不赞成使用。使用 MutationObserver 替代。360,%25E7%2599%25BE%25E5%25BA%25A6%25E7%25BD%2591%25E7%259B%2598,%25E5%25BE%25AE%25E7%259B%2598%25E9%2593%25BE%25E6%258E%25A5.user.js:35:16
Array [ "//msg.115.com/bridge_assets.html", "msg", "load" ] "http://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1471341746240_2&_t1471341746240"assets.115.com:4:41073
Array [ "//im37.115.com/chat/bridge", "connect" ] 加载bridge-connectassets.115.com:4:41073
所用的 Mutation Events 已不赞成使用。使用 MutationObserver 替代。360,%25E7%2599%25BE%25E5%25BA%25A6%25E7%25BD%2591%25E7%259B%2598,%25E5%25BE%25AE%25E7%259B%2598%25E9%2593%25BE%25E6%258E%25A5.user.js:35:16
Array [ "//im37.115.com/chat/bridge", "connect", "load" ] "http://im37.115.com/chat/bridge?cb_key=iframe_cb_key__1471341746517_3&_t1471341746517"assets.115.com:4:41073
Array [ "//im37.115.com/chat/bridge", "connect" ] "加载bridge-connect-成功 http://im37.115.com/chat/bridge?cb_key=iframe_cb_key__1471341746517_3&_t1471341746517 : http://im37.115.com/chat/bridge?cb_key=iframe_cb_key__1471341746517_3&_t1471341746517"assets.115.com:4:41073
https://github.com/kkHAIKE/fake115/issues : Unable to run script because scripts are blocked internally.（未知）
getElementById() 被传递了空字符串参数。frameworks-ff9877ee49c73cb51e41545b924373427284ddceb2cd726e19ad79070a189212.js:9:5927
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
https://github.com/kkHAIKE/fake115/issues/new : Unable to run script because scripts are blocked internally.（未知）
getElementById() 被传递了空字符串参数。frameworks-ff9877ee49c73cb51e41545b924373427284ddceb2cd726e19ad79070a189212.js:9:5927
getScripts
Parsing getScripts: 9msec
load chrome://browser/content/places/places.xul
loadSubScript: copybookmark.uc.js
loadOverlay: ExportHTMLFolderMod.uc.xul
getScripts
Parsing getScripts: 8msec
load chrome://devtools/content/webconsole/webconsole.xul
getScripts
Parsing getScripts: 8msec
load chrome://devtools/content/webconsole/webconsole.xul

**Comment by kkHAIKE** [comment]
我在firefox46下正常。。

**Comment by dsyo2008** [comment]
先备份，再升48看看是不是问题？我这里不行

**Comment by kkHAIKE** [comment]
https://github.com/feross/buffer/issues/131
