### ISSUE TITLE
Firefox 57 beta10 使用账号密码无法登陆115

### ISSUE THREAD

**Issue by mzxwt** [kkHAIKE/fake115#51]
Firefox 57 beta10 使用账号密码无法登陆115，不知道有没修复计划。
系统： Windows 10 专业版 x86
浏览器：Firefox 57 beta 10 32位
脚本加载扩展：Tampermonkey 4.5.5570
其它扩展：无
现象：使用账号密码登陆后，页面不自动刷新，点击登陆按钮总处于加载状态，无法使用账号密码登陆。Chrome下使用正常。

**Comment by adam1x** [comment]
尝试删除脚本后重新加入。由于作者上次commit没有更新版本号，所以Tampermonkey可能忽略了更新。

**Comment by kkHAIKE** [comment]
我更新到了 Firefox 58 根本没法刷新脚本缓存啊，怎么改都是老的

**Comment by yaojiwei520** [comment]
Version 57.0.2, 现象：使用账号密码登陆后，页面不自动刷新，点击登陆按钮总处于加载状态，无法使用账号密码登陆

**Comment by kkHAIKE** [comment]
火狐57以上的确有这个问题，还在调
