### ISSUE TITLE
rawgit.com可以用raw.github.com替代

### ISSUE THREAD

**Issue by yxok200** [kkHAIKE/fake115#57]
rawgit.com可以用raw.github.com替代

我这里是教育网、电信双线，2个都屏蔽了rawgit.com
但是raw.github.com正常

手动替换地址后一切正常，再次感谢大大的分享

**Comment by kkHAIKE** [comment]
👍，但是除了 rawgit.com，其他的 raw 好像都是 "Content-Type:text/plain"，为了保险还是不替换版本中的链接，rawgit.com 被强的可以用这个方法

**Comment by yxok200** [comment]
这个应该没关系的吧，text/plain只是无格式而已，不影响运行的吧

**Comment by kkHAIKE** [comment]
之前嵌js养成习惯了，嵌js必须 type 为 javascript 才执行
我先提交，让大家测过主流浏览器先
