### ISSUE TITLE
无法正常使用115

### ISSUE THREAD

**Issue by sino1641** [kkHAIKE/fake115#6]

**Comment by sino1641** [comment]
补图片 
登录后点开文件无显示空白
![115](http://ww3.sinaimg.cn/large/4e077b55gw1f740zx5yl5j21090lcdhw.jpg)

**Comment by kkHAIKE** [comment]
浏览器版本是什么。。。我觉得是你浏览器兼容问题。。只要正确跳转了基本就没插件什么事情了。这种情况我原来调试时候大概是出现cookies设置问题，请检查你cookies权限之类的

**Comment by sino1641** [comment]
chrome54
没动过任何有关cookies权限的设置。
使用手机扫码正常。

**Comment by kkHAIKE** [comment]
chromium 54.0.2824.2 测试正常

**Comment by kkHAIKE** [comment]
https://github.com/kkHAIKE/fake115/issues/14
