### ISSUE TITLE
没有登录框了……

### ISSUE THREAD

**Issue by w0330t** [kkHAIKE/fake115#60]
### 我能否访问/Ping通 rawgit.com (最近地方 DNS 有屏蔽此域名)
可以
### 我是否点击了主界面 "使用帐号登录"，重复刷新了几次
已经点击过，刷新3次以上
### 我的操作系统是，版本是
Windows 10 企业版 1803
### 我的浏览器是，版本是
Google Chrome 
版本 67.0.3396.62（正式版本） （64 位）
### 我的油猴插件是，版本是
 4.6
### 我的控制台日志如下 (firefox 用户请拷贝 Ctrl+Shift+J 界面中的内容)
![default](https://user-images.githubusercontent.com/4970238/40715475-433af358-6438-11e8-80b1-61dbcc2ee6d9.PNG)

### 我遇到了什么问题，截图
![default](https://user-images.githubusercontent.com/4970238/40715508-5d6514c0-6438-11e8-87af-78aae53bd99f.PNG)

**Comment by kkHAIKE** [comment]
能发个你的脚本界面编辑的图吗

w0330t <notifications@github.com>于2018年5月30日 周三18:36写道：

**Comment by w0330t** [comment]
![default](https://user-images.githubusercontent.com/4970238/40720064-1a92fa1c-6448-11e8-9979-175f6b4cedd6.PNG)
有个红叉提示的语法错误，是这个问题？

**Comment by w0330t** [comment]
哦……抱歉，文件搞错了，不好意思~~
