### ISSUE TITLE
无法显示登录界面

### ISSUE THREAD

**Issue by zlhdd108** [kkHAIKE/fake115#61]
# 不遵守规范直接 close

### 我能否访问/Ping通 rawgit.com (最近地方 DNS 有屏蔽此域名)
能
### 我是否点击了主界面 "使用帐号登录"，重复刷新了几次
用Ctrl+F5刷新了3次
### 我的操作系统是，版本是
win10x64 1803
### 我的浏览器是，版本是
Chrome/66.0.3359.170
### 我的油猴插件是，版本是
v4.2.5291
### 我的控制台日志如下 (firefox 用户请拷贝 Ctrl+Shift+J 界面中的内容)
![1151](https://user-images.githubusercontent.com/16465666/42076528-20fc4c56-7ba8-11e8-826f-0820ba5429d9.jpg)
![1152](https://user-images.githubusercontent.com/16465666/42076535-26296d6c-7ba8-11e8-85dd-3e5561fa3587.jpg)

### 我遇到了什么问题，截图
![1152](https://user-images.githubusercontent.com/16465666/42076541-2c103878-7ba8-11e8-8955-51dc6ccc8a25.jpg)
![1151](https://user-images.githubusercontent.com/16465666/42076545-2c436338-7ba8-11e8-9df6-1cb405e3000b.jpg)

**Comment by betterdoitnow** [comment]
同无法显示登陆界面

**Comment by IsoaSFlus** [comment]
碰到同样的问题

**Comment by kkHAIKE** [comment]
应该升级了接口，我会跟进

IsoaSFlus <notifications@github.com>于2018年6月29日 周五19:47写道：

**Comment by 990721830** [comment]
+1069惹

**Comment by NiesmialyGosc** [comment]
@zsx0731 
![my phone number](https://user-images.githubusercontent.com/40756687/42153932-0fa22ba8-7e17-11e8-996c-b4b03bd036e1.png) 为啥我输入我手机号和密码后被告知“参数传递错误！”啊？我手机版115客户端上用的也是这个手机号和密码登录的，为啥这里就不行？谢谢了！

**Comment by NiesmialyGosc** [comment]
另外，咱用了油猴之后在Chrome上登录进去能突破115网盘的上传文件大小限制吗？我是为了在公司上传1G多的文件，但又没法跟网管要求安装115网盘，才不得不使用这方案的。哪位达人能告知现在用fake115能上传1G多和2G多的文件吗？谢谢了！

**Comment by LArctic** [comment]
感谢修复。
