### ISSUE TITLE
能增加支持Violentmonkey暴力猴吗?

### ISSUE THREAD

**Issue by 990721830** [kkHAIKE/fake115#63]
![snipaste20180708_152035](https://user-images.githubusercontent.com/25548230/42417670-9478ee8e-82c2-11e8-9448-2a2a4136e945.jpg)
Win10     360极速63内核
为了一个网站开2个拓展总觉得怪怪的......
虽然有二管家可以自动.......

https://violentmonkey.github.io/get-it/
https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag

**Comment by kkHAIKE** [comment]
现已支持

**Comment by 990721830** [comment]
好的...我试一下

**Comment by 990721830** [comment]
可以了.......
