### ISSUE TITLE
无法登陆不显示登陆界面

### ISSUE THREAD

**Issue by 1990chs** [kkHAIKE/fake115#64]
# 不遵守规范直接 close

### 我的控制台日志如下 (firefox 用户请拷贝 Ctrl+Shift+J 界面中的内容)
pre-main prep time: 3 ms
VM1669:3 Error running script: fake 115Browser
ReferenceError: cloneInto is not defined
cloneInto is not defined
l @ VM1669:3
(anonymous) @ VM1669:3
value @ VM1669:3
(anonymous) @ VM1670:1
(anonymous) @ VM1670:1
b.d @ VM1666:1
Inject @ VM1666:1
e @ VM1666:1
(anonymous) @ VM1666:1
a @ VM1669:3
(anonymous) @ VM1669:3
t @ VM1669:3
o @ VM1669:3
LoadScripts @ VM1669:3
r @ VM1669:3
(anonymous) @ VM1669:3
d @ VM1666:1
(anonymous) @ VM1666:1
(anonymous) @ VM1666:1
a @ VM1664:1
(anonymous) @ VM1664:1
r.callFunc @ VM1664:1
(anonymous) @ VM1664:1
s @ VM1664:1
t @ VM1664:1
e @ VM1666:1
(anonymous) @ VM1666:1
a @ VM1669:3
(anonymous) @ VM1669:3
t.default @ VM1669:3
(anonymous) @ VM1669:6
b.d @ VM1666:1
b @ VM1666:1
(anonymous) @ VM1666:1
a @ VM1664:1
(anonymous) @ VM1664:1
r.callFunc @ VM1664:1
(anonymous) @ VM1664:1
s @ VM1664:1
t @ VM1664:1
a @ VM1664:1
(anonymous) @ VM1664:1
r.callFunc @ VM1664:1
(anonymous) @ VM1664:1
s @ VM1664:1
t @ VM1664:1
a @ VM1664:1
(anonymous) @ VM1664:1
r.callFunc @ VM1664:1
(anonymous) @ VM1664:1
s @ VM1664:1
t @ VM1664:1
a @ VM1664:1
(anonymous) @ VM1664:1
r.callFunc @ VM1664:1
(anonymous) @ VM1664:1
s @ VM1664:1
t @ VM1664:1
(anonymous) @ VM1664:1
VM1707:23 Uncaught SyntaxError: Illegal return statement
VM1668 template.js?v=1531378441:3 GET about:blank net::ERR_UNKNOWN_URL_SCHEME
Dt @ VM1668 template.js?v=1531378441:3
css @ VM1668 template.js?v=1531378441:3
show @ VM1668 template.js?v=1531378441:3
(anonymous) @ (index):1261
d @ VM1668 template.js?v=1531378441:1
fireWith @ VM1668 template.js?v=1531378441:1
ready @ VM1668 template.js?v=1531378441:1
a @ VM1668 template.js?v=1531378441:1
VM1728 z_stat.php?id=1256793290&web_id=1256793290:16 Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
na @ VM1728 z_stat.php?id=1256793290&web_id=1256793290:16
Ga @ VM1728 z_stat.php?id=1256793290&web_id=1256793290:12
(anonymous) @ VM1728 z_stat.php?id=1256793290&web_id=1256793290:23
(anonymous) @ VM1728 z_stat.php?id=1256793290&web_id=1256793290:23
VM1706:29 Uncaught TypeError: Cannot read property 'indexOf' of null
    at Object.attrObserver (<anonymous>:29:69)
    at MutationObserver.<anonymous> (<anonymous>:137:402)
attrObserver @ VM1706:29
(anonymous) @ VM1706:137
attributes (async)
hide @ VM1668 template.js?v=1531378441:3
(anonymous) @ (index):208
dispatch @ VM1668 template.js?v=1531378441:2
s @ VM1668 template.js?v=1531378441:2
reg.html:8 GET https://www.googletagmanager.com/gtag/js?id=UA-102646709-1 net::ERR_CONNECTION_TIMED_OUT
reg.html:8 GET https://www.googletagmanager.com/gtag/js?id=UA-102646709-1 net::ERR_CONNECTION_TIMED_OUT
Navigated to http://115.com/
:sourcemap:38 pre-main prep time: 5 ms
VM1987:3 Error running script: fake 115Browser
ReferenceError: cloneInto is not defined
cloneInto is not defined
l @ VM1987:3
(anonymous) @ VM1987:3
value @ VM1987:3
(anonymous) @ VM1988:1
(anonymous) @ VM1988:1
b.d @ VM1986:1
Inject @ VM1986:1
e @ VM1986:1
(anonymous) @ VM1986:1
a @ VM1987:3
(anonymous) @ VM1987:3
t @ VM1987:3
o @ VM1987:3
LoadScripts @ VM1987:3
r @ VM1987:3
(anonymous) @ VM1987:3
d @ VM1986:1
(anonymous) @ VM1986:1
(anonymous) @ VM1986:1
a @ VM1984:1
(anonymous) @ VM1984:1
r.callFunc @ VM1984:1
(anonymous) @ VM1984:1
s @ VM1984:1
t @ VM1984:1
e @ VM1986:1
(anonymous) @ VM1986:1
a @ VM1987:3
(anonymous) @ VM1987:3
t.default @ VM1987:3
(anonymous) @ VM1987:6
b.d @ VM1986:1
b @ VM1986:1
(anonymous) @ VM1986:1
a @ VM1984:1
(anonymous) @ VM1984:1
r.callFunc @ VM1984:1
(anonymous) @ VM1984:1
s @ VM1984:1
t @ VM1984:1
a @ VM1984:1
(anonymous) @ VM1984:1
r.callFunc @ VM1984:1
(anonymous) @ VM1984:1
s @ VM1984:1
t @ VM1984:1
a @ VM1984:1
(anonymous) @ VM1984:1
r.callFunc @ VM1984:1
(anonymous) @ VM1984:1
s @ VM1984:1
t @ VM1984:1
a @ VM1984:1
(anonymous) @ VM1984:1
r.callFunc @ VM1984:1
(anonymous) @ VM1984:1
s @ VM1984:1
t @ VM1984:1
(anonymous) @ VM1984:1
??libs/jquery-1.7.2.js,oofUtil.js,paths.js,oofUtil/validate.js,oofUtil/cookies.js,oofUtil/stringHelper.js,shell.js,plug/copy/copy.js,oofUtil/template.js?v=1531378441:3 XHR finished loading: GET "http://home.115.com/api/1.0/web/1.0/topic/get_other_xds?type=bannernologion".
send @ ??libs/jquery-1.7.2.js,oofUtil.js,paths.js,oofUtil/validate.js,oofUtil/cookies.js,oofUtil/stringHelper.js,shell.js,plug/copy/copy.js,oofUtil/template.js?v=1531378441:3
ajax @ ??libs/jquery-1.7.2.js,oofUtil.js,paths.js,oofUtil/validate.js,oofUtil/cookies.js,oofUtil/stringHelper.js,shell.js,plug/copy/copy.js,oofUtil/template.js?v=1531378441:3
(anonymous) @ (index):34
VM2027:23 Uncaught SyntaxError: Illegal return statement
??libs/jquery-1.7.2.js,oofUtil.js,paths.js,oofUtil/validate.js,oofUtil/cookies.js,oofUtil/stringHelper.js,shell.js,plug/copy/copy.js,oofUtil/template.js?v=1531378441:3 GET about:blank net::ERR_UNKNOWN_URL_SCHEME
Dt @ ??libs/jquery-1.7.2.js,oofUtil.js,paths.js,oofUtil/validate.js,oofUtil/cookies.js,oofUtil/stringHelper.js,shell.js,plug/copy/copy.js,oofUtil/template.js?v=1531378441:3
css @ ??libs/jquery-1.7.2.js,oofUtil.js,paths.js,oofUtil/validate.js,oofUtil/cookies.js,oofUtil/stringHelper.js,shell.js,plug/copy/copy.js,oofUtil/template.js?v=1531378441:3
show @ ??libs/jquery-1.7.2.js,oofUtil.js,paths.js,oofUtil/validate.js,oofUtil/cookies.js,oofUtil/stringHelper.js,shell.js,plug/copy/copy.js,oofUtil/template.js?v=1531378441:3
(anonymous) @ (index):1261
d @ ??libs/jquery-1.7.2.js,oofUtil.js,paths.js,oofUtil/validate.js,oofUtil/cookies.js,oofUtil/stringHelper.js,shell.js,plug/copy/copy.js,oofUtil/template.js?v=1531378441:1
fireWith @ ??libs/jquery-1.7.2.js,oofUtil.js,paths.js,oofUtil/validate.js,oofUtil/cookies.js,oofUtil/stringHelper.js,shell.js,plug/copy/copy.js,oofUtil/template.js?v=1531378441:1
ready @ ??libs/jquery-1.7.2.js,oofUtil.js,paths.js,oofUtil/validate.js,oofUtil/cookies.js,oofUtil/stringHelper.js,shell.js,plug/copy/copy.js,oofUtil/template.js?v=1531378441:1
a @ ??libs/jquery-1.7.2.js,oofUtil.js,paths.js,oofUtil/validate.js,oofUtil/cookies.js,oofUtil/stringHelper.js,shell.js,plug/copy/copy.js,oofUtil/template.js?v=1531378441:1
z_stat.php?id=1256793290&web_id=1256793290:16 Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
na @ z_stat.php?id=1256793290&web_id=1256793290:16
Ga @ z_stat.php?id=1256793290&web_id=1256793290:12
(anonymous) @ z_stat.php?id=1256793290&web_id=1256793290:23
(anonymous) @ z_stat.php?id=1256793290&web_id=1256793290:23
reg.html:8 GET https://www.googletagmanager.com/gtag/js?id=UA-102646709-1 net::ERR_CONNECTION_TIMED_OUT

**Comment by kkHAIKE** [comment]
您用的是 Violentmonkey 吗

**Comment by 1990chs** [comment]
用的暴力候 @kkHAIKE

**Comment by kkHAIKE** [comment]
https://github.com/kkHAIKE/fake115/issues/53
