### ISSUE TITLE
上传文件无法突破1GB

### ISSUE THREAD

**Issue by NiesmialyGosc** [kkHAIKE/fake115#66]
# 不遵守规范直接 close

### 我能否访问/Ping通 rawgit.com (最近地方 DNS 有屏蔽此域名)
能
### 我是否点击了主界面 "使用帐号登录"，重复刷新了几次
是，一次
### 我的操作系统是，版本是
Windows 7 Enterprise
Version 6.1 (Build 7601: Service Pack1)
### 我的浏览器是，版本是
Google Chrome 版本 67.0.3396.99（正式版本）
### 我的油猴插件是，版本是
Tampermonkey v4.6
### 我的控制台日志如下 (firefox 用户请拷贝 Ctrl+Shift+J 界面中的内容)
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 没有登录不再请求
userscript.html?id=fdadec1a-47d1-46f6-9e65-fd712b102dc1:36 pre-main prep time: 2 ms
util-min.js?_vh=fd24452_5:1 115浏览器状态
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 (2) ["//q.115.com/bridge_assets.html", "q"]0: "//q.115.com/bridge_assets.html"1: "q"length: 2__proto__: Array(0) "加载bridge-q"
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 (2) ["//q.115.com/bridge_assets.html", "q"]0: "//q.115.com/bridge_assets.html"1: "q"length: 2__proto__: Array(0) "加载bridge-q-成功 http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1534997733559_0&_t1534997733559 : http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1534997733559_0&_t1534997733559"
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 (2) ["iframe_cb_key__1534997733559_0", 1]0: "iframe_cb_key__1534997733559_0"1: 1length: 2__proto__: Array(0)
userscript.html?id=fdadec1a-47d1-46f6-9e65-fd712b102dc1:36 pre-main prep time: 2 ms
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 (3) ["//q.115.com/bridge_assets.html", "q", "load"]0: "//q.115.com/bridge_assets.html"1: "q"2: "load"length: 3__proto__: Array(0) "http://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1534997733559_0&_t1534997733559"
util-min.js?_vh=fd24452_5:1 初始化UI
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 正常请求红点
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 正常请求红点
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 正常请求红点
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 正常请求红点
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 正常请求红点
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 正常请求红点
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 正常请求红点
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 正常请求红点
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 正常请求红点
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 正常请求红点
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 正常请求红点
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1534933336:3 正常请求红点
### 我遇到了什么问题，截图
![scr](https://user-images.githubusercontent.com/40756687/44504555-242a6780-a6cf-11e8-82cb-91c12625f684.png)
我已经用了站长的UPLOAD_CONFIG_H5.__defineGetter__()那段方法，可以在Chrome里上传超过200MB但小于1GB的文件了，但依然只要上传文件大小突破1GB哪怕只超过1B，就无法上传，始终碰到“网络异常”报错，恳请教我在Chrome浏览器里上传文件突破1GB的方法，谢谢了！

**Comment by kkHAIKE** [comment]
这个超出本插件的范畴了，因为有 rar储存分卷 替代等方式
囧，这里没有“站长”、“版主”，只有 repo主
