### ISSUE TITLE
用Chrome无法一次性全选并下载多个文件怎么办啊

### ISSUE THREAD

**Issue by NiesmialyGosc** [kkHAIKE/fake115#67]
# 不遵守规范直接 close

### 我能否访问/Ping通 rawgit.com (最近地方 DNS 有屏蔽此域名)
能
### 我是否点击了主界面 "使用帐号登录"，重复刷新了几次
是，没刷新
### 我的操作系统是，版本是
Win7 Enterprise SP1
### 我的浏览器是，版本是
Chrome 版本 69.0.3497.100（正式版本） （64 位）
### 我的油猴插件是(Violent/Grease/Tamper)monkey，版本是
Tampermonkey v4.7
### 我的控制台日志如下 (firefox 用户请拷贝 Ctrl+Shift+J 界面中的内容)
无
### 我遇到了什么问题，截图
没法一次性下载多个文件，点了“下载”没反应
![download](https://user-images.githubusercontent.com/40756687/47058521-fefe3500-d1f7-11e8-897c-0a92c0d4ed25.png)

**Comment by kkHAIKE** [comment]
首先，这个功能是 115浏览器 原生支持的，用 js 做不到这点
其次，从你使用 115 的习惯（大量零碎文件不使用压缩包），原生 115 更适合你

**Comment by CaiPeterCai** [comment]
你不会用aria?
https://chrome.google.com/webstore/detail/115exporter/ojafklbojgenkohhdgdjeaepnbjffdjf
