### ISSUE TITLE
好像失效了

### ISSUE THREAD

**Issue by 815169876** [kkHAIKE/fake115#68]

**Comment by zzzop** [comment]
暴力猴可以，Tampermonkey不行

**Comment by kkHAIKE** [comment]
> 暴力猴可以，Tampermonkey不行
> chrome 71.0.3578.98

Tampermonkey 4.7.54
Chrome 71.0.3578.98
win10 x64 测试通过

**Comment by zzzop** [comment]
> > 暴力猴可以，Tampermonkey不行
> > chrome 71.0.3578.98
> 
> Tampermonkey 4.7.54
> Chrome 71.0.3578.98
> win10 x64 测试通过

发现了，是https://greasyfork.org/en/scripts/24508-userscript-show-site-all-userjs这个插件打开就不行
chrome 71.0.3578.98
Tampermonkey 4.7.63
