### ISSUE TITLE
网页界面出现乱码

### ISSUE THREAD

**Issue by ZerOri** [kkHAIKE/fake115#69]
# 不遵守规范直接 close

### 我能否访问/Ping通 rawgit.com (最近地方 DNS 有屏蔽此域名)
可访问rawgit.com，但ping不通
### 我是否点击了主界面 "使用帐号登录"，重复刷新了几次
是
### 我的操作系统是，版本是
win10 1809
### 我的浏览器是，版本是
chrome 71
### 我的油猴插件是Tamper monkey，版本是
4.7
### 我的控制台日志如下 (firefox 用户请拷贝 Ctrl+Shift+J 界面中的内容)
[115.com-1547748374805.log](https://github.com/kkHAIKE/fake115/files/2769984/115.com-1547748374805.log)

### 我遇到了什么问题，截图
![99c7eef0-26ab-47be-a9a8-e3379aa9e7de png](https://user-images.githubusercontent.com/46775615/51338605-374a3380-1ac5-11e9-81a6-9efd9bda9bfc.jpg)
如图，云下载旁的按钮，希望能修复界面

**Comment by kkHAIKE** [comment]
哪个按钮是乱码，确认不是秒传功能的那个按钮吗

Zero O <notifications@github.com>于2019年1月18日 周五02:07写道：
