### ISSUE TITLE
没有跳转

### ISSUE THREAD

**Issue by jackiejtr** [kkHAIKE/fake115#7]
连密码框都没出啊。。

**Comment by kkHAIKE** [comment]
切换下二维码登录，115账号登陆的tab

**Comment by jackiejtr** [comment]
然后登陆就一直正在登陆= =

**Comment by kkHAIKE** [comment]
多试几次，因为有链接到github的js，有时候网络问题会连不上

**Comment by kkHAIKE** [comment]
https://github.com/kkHAIKE/fake115/issues/14
