### ISSUE TITLE
2019/6/18 脚本已失效

### ISSUE THREAD

**Issue by 1614299693** [kkHAIKE/fake115#71]
# 不遵守规范直接 close

### 我能否访问/Ping通 rawgit.com (最近地方 DNS 有屏蔽此域名)
否
### 我是否点击了主界面 "使用帐号登录"，重复刷新了几次
是
### 我的操作系统是，版本是
Win10 1803 Build-17134.829
### 我的浏览器是，版本是
Chrome 64bit 74.0.3729.169
### 我的油猴插件是(Violent/Grease/Tamper)monkey，版本是
Tamper)monkey Ver4.9.5941 
### 我的控制台日志如下 (firefox 用户请拷贝 Ctrl+Shift+J 界面中的内容)
![image](https://user-images.githubusercontent.com/30307838/59682172-39e1be00-9208-11e9-9be8-9e33d092bee8.png)
### 我遇到了什么问题，截图
点击登陆后无效

**Comment by IsoaSFlus** [comment]
我这边没有问题，你检查下你自己的环境吧。

**Comment by BraveSail** [comment]
我这边也失效，刷新100次没有用

**Comment by gu20124848** [comment]
截图怎样上传至issues？

**Comment by zzzop** [comment]
你把Tampermonkey禁用然后换暴力猴试试
