### ISSUE TITLE
用户认证异常...

### ISSUE THREAD

**Issue by Noah1995** [kkHAIKE/fake115#73]
# 不遵守规范直接 close

### 我能否访问/Ping通 rawgit.com (最近地方 DNS 有屏蔽此域名)

可以通

### 我是否点击了主界面 "使用帐号登录"，重复刷新了几次

是的

### 我的操作系统是，版本是

win10

### 我的浏览器是，版本是

cent beta 78内核

### 我的油猴插件是(Violent/Grease/Tamper)monkey，版本是

暴力猴v2.12.2

### 我遇到了什么问题，截图

最近几天开始的...
上个星期还是好的.....
用户认证异常...
app帐号登录是好的..
网页扫码也是好的...
![【Snipaste】【2019-11-30】No 015737](https://user-images.githubusercontent.com/25548230/69884757-d4e0d700-1314-11ea-9a4f-e578b7f8e0a5.jpg)

**Comment by trulynb** [comment]
同样的问题  现在只能手机app扫二维码进来了

**Comment by kkHAIKE** [comment]
经测试确实失效。。等待更新(肯定是年底冲kpi)

**Comment by kkHAIKE** [comment]
原因 https://github.com/violentmonkey/violentmonkey/releases/tag/v2.12.2
之前因为暴力猴不支持 binary 用了个兼容的做法。现在支持了
