### ISSUE TITLE
115改版后 功能异常

### ISSUE THREAD

**Issue by gongdao123** [kkHAIKE/fake115#74]
# 不遵守规范直接 close

### 我能否访问/Ping通 rawgit.com (最近地方 DNS 有屏蔽此域名)
是的

### 我是否点击了主界面 "使用帐号登录"，重复刷新了几次
是的

### 我的操作系统是，版本是
macOS 10.14.6

### 我的浏览器是，版本是
Google Chrome Version 79.0.3945.88 (Official Build) (64-bit)

### 我的油猴插件是(Violent/Grease/Tamper)monkey，版本是
1.3.8

### 我的控制台日志如下 (firefox 用户请拷贝 Ctrl+Shift+J 界面中的内容)
`
Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at home.js:1
offline5.0.js?_vh=8d9da36_6&_=1576750944526:1 lixianTasklistUpdate
main-wl-2014-min.js?_vh=12bc326_6:1 a7f5522692bd0074a28bf2b18b066530f7ac8a48___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 d4802011b209001045854e411a6f67d7e640b305___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 db49f7b88593cf6130a9323f0248801b2d67c952___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 3db26125d4a0178e681dd569fe9889c826163b34___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 12ed653ba74b4ed53e3d8abf3348184a139b76bf___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 2bd41dc68621d4357e9d7bf34f3405e8f7dca3da___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 6e0b46934f1dfa39d1dcd0f0a68affb99c701e5f___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 f8667c8dcbcffe4496f1c2cea504b9fcb8af8631___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 d32016180c3ac42a600ec510707b10ebbeb13e18___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 d698b55cc13c97d758f8212a279b4da64b2aac66___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 cfb18926aa2a263328048c14aa2c9bfb88990248___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 fb54c3b9919129a81388b4461da9825c03676791___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 5d2b7d41c21057faa398af8c9205f85aeda5a03e___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 334df3251f3d2216bfdb00749355d19430a2e52e___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 cc223544dde9ad2debd5c8f19e28229cf50d384d___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 1872bca1746e783735b85e0b56a808afa041a90a___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 29261aaf7e59c73eae386d5741338bfdd0225b11___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 722aa9816f0c985fee59593cb54d681bef4cba4b___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 9689a29c8569b25926ea8ac3c39d6c9fb633f753___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 04db7582350d735a47c2c4c768298b6902c65a87___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 c9fce45631e2796cf4aa84c14c3c1084167838bf___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 a1e9e88dc52a525f50fb3f1855faab5b736dfb6a___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 a8670c8641010526f4bbb823cdd805c6c150f445___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 6f716bd842053c07444d29e90958f8628a2236b0___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 b571f08dab48ccd441f1dc3f55005eb2c657d8f1___100|||
main-wl-2014-min.js?_vh=12bc326_6:1 bac2c9d9c552ab2465485fd37c11877f9af051db___100|||
home.js:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at home.js:1
12??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1576746728:3 正常请求红点
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1576746728:3 正常请求红点
??libs/jquery-1.7.2.js,jquery-extend.js,libs/json2.js,oofUtil.js,paths.js,oofUtil/subscribe.js,commonFrame/urlMaintain.js,ajax/bridge.js?v=1576746728:3 正常请求红点
`

### 我遇到了什么问题，截图
由于115改版 无法正常使用。
1. 按钮错乱
<img width="1240" alt="Screen Shot 2019-12-19 at 6 32 41 PM" src="https://user-images.githubusercontent.com/18628246/71166564-043c9100-228e-11ea-8e1f-ba32d2502495.png">

2. 导出下载 按钮 功能报错

**Comment by kkHAIKE** [comment]
.....这不是本repo的功能
