### ISSUE TITLE
请教“选择文件”按钮如何去掉或者调整位置。

### ISSUE THREAD

**Issue by r2malt** [kkHAIKE/fake115#76]
请教下“选择文件”这个按钮能去掉么，或者如何调整位置。
当多层文件夹时会挡到路径行。

**Comment by kkHAIKE** [comment]
411: js_top_panel_box = unsafeWindow.document.getElementById('js_top_panel_box');
右边的字符串随便改改

**Comment by r2malt** [comment]
多谢多谢！！！
