### ISSUE TITLE
请问MAXTHON 5.0 装暴力猴 能用吗  

### ISSUE THREAD

**Issue by xshj11** [kkHAIKE/fake115#8]
之前一直用这位同学的脚本 但是失效了http://tieba.baidu.com/p/4370867867
fake115   在MAXTHON 5.0 暴力猴 后没显示登录框 还是我打开方式不对？

**Comment by kkHAIKE** [comment]
https://github.com/kkHAIKE/fake115/issues/7

**Comment by kkHAIKE** [comment]
https://github.com/kkHAIKE/fake115/issues/14
