### ISSUE TITLE
界面和acgotaku的115助手冲突

### ISSUE THREAD

**Issue by wutongskype** [kkHAIKE/fake115#80]
115助手地址 https://github.com/acgotaku/115
那个选择文件的东东跟上面的按钮重叠,见下图
![image](https://user-images.githubusercontent.com/40192806/87947224-9aab8c00-cad5-11ea-8fb5-3921fd6f1dea.png)

**Comment by kkHAIKE** [comment]
https://github.com/kkHAIKE/fake115/issues/76
