### ISSUE TITLE
 昨天晚上开始，aria2 rpc 无法获取115的下载地址

### ISSUE THREAD

**Issue by opfans** [kkHAIKE/fake115#82]
昨天晚上开始，aria2 rpc 无法获取115的下载地址，不能用ARIA2下载115文件了

**Comment by IsoaSFlus** [comment]
115关闭了浏览器下载
![image](https://user-images.githubusercontent.com/5125031/101228746-fb7bdf80-36d7-11eb-9936-ad7287c58e04.png)

**Comment by opfans** [comment]
看到了，是的，关闭了，逼我们用他客户端。现在客户端下载还会丢包吗



---原始邮件---
发件人: "IsoaSFlus"<notifications@github.com&gt;
发送时间: 2020年12月5日(周六) 上午8:58
收件人: "kkHAIKE/fake115"<fake115@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Y3Y4"<392814736@qq.com&gt;;
主题: Re: [kkHAIKE/fake115]  昨天晚上开始，aria2 rpc 无法获取115的下载地址 (#82)




 
115关闭了浏览器下载

**Comment by IsoaSFlus** [comment]
从没用过他的客户端，我的系统也不装不了他的客户端。。。。可怜我的还有好几年的会员

**Comment by opfans** [comment]
下载小文件，比如图片可以。大文件不行，比如蓝光原盘。你有方法解决吗



---原始邮件---
发件人: "IsoaSFlus"<notifications@github.com&gt;
发送时间: 2020年12月5日(周六) 上午8:58
收件人: "kkHAIKE/fake115"<fake115@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Y3Y4"<392814736@qq.com&gt;;
主题: Re: [kkHAIKE/fake115]  昨天晚上开始，aria2 rpc 无法获取115的下载地址 (#82)




 
115关闭了浏览器下载

**Comment by kkHAIKE** [comment]
这么艹蛋的。。。最近放开了登录了，我以为可以退休了，现在来这一套？

**Comment by Bitomancer** [comment]
有什么进度吗？ 现在用不了了

**Comment by AltriaPendrag0n** [comment]
115那个浏览器用的也是chrome的内核吧？不知道大佬们有么有什么办法

**Comment by kkHAIKE** [comment]
看了下，要用 js 模拟两个 native 接口
browserInterface.CreateDownloadTask
browserInterface.CreateSharedTask
有加密比较麻烦，和之前的登录类似

**Comment by lvzhenbo** [comment]
大佬，加油！我们等着，看你和雪月秋水哪方先搞出来

**Comment by xepo12** [comment]
坐等更新。
我用motrix

**Comment by opfans** [comment]
我认为，先不要急着破解，等他消停之后破解。现在解决了，过几天估计又会封杀。



---原始邮件---
发件人: "xepo12"<notifications@github.com&gt;
发送时间: 2020年12月9日(周三) 中午1:09
收件人: "kkHAIKE/fake115"<fake115@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Y3Y4"<392814736@qq.com&gt;;
主题: Re: [kkHAIKE/fake115]  昨天晚上开始，aria2 rpc 无法获取115的下载地址 (#82)




 
坐等更新。
 我用motrix

**Comment by tonyget** [comment]
坐等大佬更新

**Comment by kkHAIKE** [comment]
实现了一个版本，大家可以试试

**Comment by lvzhenbo** [comment]
第一时间来体验，但怎么用啊，代码里能看到文件下载入口，但实际使用没有看到入口

**Comment by q741451** [comment]
> 实现了一个版本，大家可以试试

![QQ拼音截图20201211164405](https://user-images.githubusercontent.com/1047371/101882077-5037c280-3bd0-11eb-8376-ed956ef6bdcd.png)

大神！成功了！！！坐等隔壁跟上移植(づ￣ 3￣)づ

**Comment by kkHAIKE** [comment]
> 第一时间来体验，但怎么用啊，代码里能看到文件下载入口，但实际使用没有看到入口

直接找文件点击下载

**Comment by lvzhenbo** [comment]
> > 第一时间来体验，但怎么用啊，代码里能看到文件下载入口，但实际使用没有看到入口
> 
> 直接找文件点击下载

点了，然后显示启动115客户端，失败就弹出要求下载115客户端
![屏幕截图 2020-12-11 165338.png](https://i.loli.net/2020/12/11/egS37WA5DOnFY64.png)
![屏幕截图 2020-12-11 165330.png](https://i.loli.net/2020/12/11/Y793lZrFHjTpGAC.png)

**Comment by kkHAIKE** [comment]
> > > 第一时间来体验，但怎么用啊，代码里能看到文件下载入口，但实际使用没有看到入口
> > 
> > 
> > 直接找文件点击下载
> 
> 点了，然后显示启动115客户端，失败就弹出要求下载115客户端
> ![屏幕截图 2020-12-11 165338.png](https://camo.githubusercontent.com/918b668d901c8b6217e048852ab1d06f986af147d2bac3136615dce1c6235fcf/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31322f31312f6567533337574135444f6e465936342e706e67)
> ![屏幕截图 2020-12-11 165330.png](https://camo.githubusercontent.com/dca73344907fcaa9e867afba3be36e316b32523ac2de2a7ab9d2b3c39c6fbe17/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31322f31312f593739336c5a7246486a54704741432e706e67)

你插件没载入，载入的话不会弹出这个对话框了

**Comment by lvzhenbo** [comment]
> > > > 第一时间来体验，但怎么用啊，代码里能看到文件下载入口，但实际使用没有看到入口
> > > 
> > > 
> > > 直接找文件点击下载
> > 
> > 
> > 点了，然后显示启动115客户端，失败就弹出要求下载115客户端
> 
> 你插件没载入，载入的话不会弹出这个对话框了

?上面的插件栏能看到脚本是开着的，而且我F12能看到进入115浏览器状态，说明脚本是成功执行的
![屏幕截图 2020-12-11 172659.png](https://i.loli.net/2020/12/11/Twyz9nKFtajpVY1.png)

**Comment by lvzhenbo** [comment]
> 1. https://rawgit.com/kkHAIKE/jsencrypt/balabala/bin/jsencrypt.js 这个链接能访问吗
> 2. 115浏览器状态 这个不是我脚本打的，现在看不到我脚本是否成功
> 3. 我脚本非常简单就是替换下载函数，如果加载成功肯定看不到原下载框了

打不开，而且百度了一下应该被墙了
https://github.com/tuna/oh-my-tuna/issues/11
这个链接有详细说明DNS被污染了

**Comment by opfans** [comment]
这里聊，会不会太高调了，去电报群聊



---原始邮件---
发件人: "吕振波"<notifications@github.com&gt;
发送时间: 2020年12月11日(周五) 晚上6:08
收件人: "kkHAIKE/fake115"<fake115@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Y3Y4"<392814736@qq.com&gt;;
主题: Re: [kkHAIKE/fake115]  昨天晚上开始，aria2 rpc 无法获取115的下载地址 (#82)




   
https://rawgit.com/kkHAIKE/jsencrypt/balabala/bin/jsencrypt.js 这个链接能访问吗 

115浏览器状态 这个不是我脚本打的，现在看不到我脚本是否成功 

我脚本非常简单就是替换下载函数，如果加载成功肯定看不到原下载框了 
  
打不开，而且百度了一下应该被墙了
 tuna/oh-my-tuna#11
 这个链接有详细说明DNS被污染了

**Comment by shang-he** [comment]
电报群是多少

**Comment by AltriaPendrag0n** [comment]
> > 1. https://rawgit.com/kkHAIKE/jsencrypt/balabala/bin/jsencrypt.js 这个链接能访问吗
> > 2. 115浏览器状态 这个不是我脚本打的，现在看不到我脚本是否成功
> > 3. 我脚本非常简单就是替换下载函数，如果加载成功肯定看不到原下载框了
> 
> 打不开，而且百度了一下应该被墙了
> [tuna/oh-my-tuna#11](https://github.com/tuna/oh-my-tuna/issues/11)
> 这个链接有详细说明DNS被污染了

https://raw.github.com/kkHAIKE/jsencrypt/balabala/bin/jsencrypt.js
把脚本的第12行替换为这个地址就可以了

**Comment by AltriaPendrag0n** [comment]
> 这里聊，会不会太高调了，去电报群聊
> […](#)
> ---原始邮件--- 发件人: "吕振波"<notifications@github.com&gt; 发送时间: 2020年12月11日(周五) 晚上6:08 收件人: "kkHAIKE/fake115"<fake115@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"Y3Y4"<392814736@qq.com&gt;; 主题: Re: [kkHAIKE/fake115] 昨天晚上开始，aria2 rpc 无法获取115的下载地址 (#82) https://rawgit.com/kkHAIKE/jsencrypt/balabala/bin/jsencrypt.js 这个链接能访问吗 115浏览器状态 这个不是我脚本打的，现在看不到我脚本是否成功 我脚本非常简单就是替换下载函数，如果加载成功肯定看不到原下载框了 打不开，而且百度了一下应该被墙了 [tuna/oh-my-tuna#11](https://github.com/tuna/oh-my-tuna/issues/11) 这个链接有详细说明DNS被污染了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬求个电报群代码

**Comment by kkHAIKE** [comment]
起了一个新脚本，之前的登录还保留

**Comment by lvzhenbo** [comment]
> > > 1. https://rawgit.com/kkHAIKE/jsencrypt/balabala/bin/jsencrypt.js 这个链接能访问吗
> > > 2. 115浏览器状态 这个不是我脚本打的，现在看不到我脚本是否成功
> > > 3. 我脚本非常简单就是替换下载函数，如果加载成功肯定看不到原下载框了
> > 
> > 
> > 打不开，而且百度了一下应该被墙了
> > [tuna/oh-my-tuna#11](https://github.com/tuna/oh-my-tuna/issues/11)
> > 这个链接有详细说明DNS被污染了
> 
> https://raw.github.com/kkHAIKE/jsencrypt/balabala/bin/jsencrypt.js
> 把脚本的第12行替换为这个地址就可以了

https://raw.githubusercontent.com/kkHAIKE/jsencrypt/balabala/bin/jsencrypt.js
应该是这个，这个可以访问

**Comment by kkHAIKE** [comment]
这两个域名各地的情况都不同

**Comment by sanguobaby** [comment]
> 这里聊，会不会太高调了，去电报群聊
> […](#)
> ---原始邮件--- 发件人: "吕振波"<notifications@github.com&gt; 发送时间: 2020年12月11日(周五) 晚上6:08 收件人: "kkHAIKE/fake115"<fake115@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"Y3Y4"<392814736@qq.com&gt;; 主题: Re: [kkHAIKE/fake115] 昨天晚上开始，aria2 rpc 无法获取115的下载地址 (#82) https://rawgit.com/kkHAIKE/jsencrypt/balabala/bin/jsencrypt.js 这个链接能访问吗 115浏览器状态 这个不是我脚本打的，现在看不到我脚本是否成功 我脚本非常简单就是替换下载函数，如果加载成功肯定看不到原下载框了 打不开，而且百度了一下应该被墙了 [tuna/oh-my-tuna#11](https://github.com/tuna/oh-my-tuna/issues/11) 这个链接有详细说明DNS被污染了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问电报群号是多少

**Comment by BIU-DAHZOU** [comment]
怎么使用啊 油猴已经添加了插件 115还是提示使用115电脑版下载 我已经捐赠了 ！！求回复！！！
![批注 2020-12-19 144450](https://user-images.githubusercontent.com/76240866/102683120-91c6ff80-41c6-11eb-8473-a14a2e49291a.png)
![批注 2020-12-19 144513](https://user-images.githubusercontent.com/76240866/102683122-925f9600-41c6-11eb-8c32-ef26ce88e922.png)
![批注 2020-12-19 144915](https://user-images.githubusercontent.com/76240866/102683124-9390c300-41c6-11eb-81ab-5240894db7b8.png)

**Comment by kkHAIKE** [comment]
使用带 d 的那个 user.js 是下载
