### ISSUE TITLE
可不可以恢复登陆模拟，以前不用输入手机验证码，现在每次登陆都要收手机短信，非常麻烦。

### ISSUE THREAD

**Issue by cnbetac** [kkHAIKE/fake115#83]
# 不遵守规范直接 close

### 我能否访问/Ping通 rawgit.com (最近地方 DNS 有屏蔽此域名)
可以

### 我是否点击了主界面 "使用帐号登录"，重复刷新了几次
是的

### 我的操作系统是，版本是
win7 64

### 我的浏览器是，版本是
firefox 82
### 我的油猴插件是(Violent/Grease/Tamper)monkey，版本是
Tamper)monkey

### 我的控制台日志如下 (firefox 用户请拷贝 Ctrl+Shift+J 界面中的内容)
.........和这个没什么关系吧- - 我也不会弄

### 我遇到了什么问题，截图
以前不用输入手机验证码，现在每次登陆都要收手机短信
![QQ截图20201211162144](https://user-images.githubusercontent.com/2510128/101879892-fda8d700-3bcc-11eb-844e-c02f2334d021.png)

**Comment by kkHAIKE** [comment]
奇怪。。。我用 chrome 不会提示短信。。。
反而用官方 115 一直用短信。。
先挂起，看看大家反馈

**Comment by kkHAIKE** [comment]
可以再建立个插件填入 
https://github.com/kkHAIKE/fake115/raw/240b6709d47476e269bfd099ca389338e6c67d05/fake115.user.js
的内容，把名称改下

**Comment by wrxx2019** [comment]
一样情况，win10+chrome最新版本，1.3.8登录不需要短信验证，1.3.9需要。已经降级

**Comment by xepo12** [comment]
建议使用这个脚本。
https://greasyfork.org/zh-CN/scripts/408466-115优化大师

**Comment by kkHAIKE** [comment]
我分开两个脚本会不会好点

**Comment by larchsis** [comment]
现在fake115d.user.js是只有伪装115下载么？原来的登录功能就用上面发的那个？
