### ISSUE TITLE
能否增加一键复制所有下载链接功能

### ISSUE THREAD

**Issue by xiaoleichen** [kkHAIKE/fake115#84]
# 不遵守规范直接 close

### 我遇到了什么问题，截图
能否增加一键复制所有下载链接功能？批量下载的方便贴到aria2.
![copy](https://user-images.githubusercontent.com/25204742/101975336-a7e62600-3bf0-11eb-9610-2bbf25d31411.JPG)

**Comment by kkHAIKE** [comment]
已提交
