### ISSUE TITLE
下载脚本已失效

### ISSUE THREAD

**Issue by xepo12** [kkHAIKE/fake115#86]
# 不遵守规范直接 close

### 我能否访问/Ping通 rawgit.com (最近地方 DNS 有屏蔽此域名)
能
### 我是否点击了主界面 "使用帐号登录"，重复刷新了几次
否
### 我的操作系统是，版本是
win 10
### 我的浏览器是，版本是
opera 73.0.3856.284
### 我的油猴插件是(Violent/Grease/Tamper)monkey，版本是
Tamper)monkey 4.11
### 我遇到了什么问题，截图
下载脚本已失效。12月14日将下载链接发送给很多人，导致封号。26号解封

**Comment by kkHAIKE** [comment]
这不是你被封了么。。。和下载脚本啥关系？

**Comment by xepo12** [comment]
115识别到了我将下载链接发送给很多人。
26号解封了，发现下载脚本已失效。
下载失败

**Comment by xepo12** [comment]
![](https://cdn.jsdelivr.net/gh/xepo12/pic@main/224nshot.jpg)

**Comment by kkHAIKE** [comment]
你普通的 115 试了可以么。。。

**Comment by xepo12** [comment]
![](https://cdn.jsdelivr.net/gh/xepo12/pic@main/33233eenshot.jpg)
用另外一个115账号，
测试发现失效

**Comment by kkHAIKE** [comment]
你 115 浏览器 + 插件?

**Comment by xepo12** [comment]
对。

**Comment by kkHAIKE** [comment]
普通115不用插件是什么样

**Comment by xepo12** [comment]
![](https://cdn.jsdelivr.net/gh/xepo12/pic@main/888nshot.jpg)
普通115不用插件,当然是限速了。100k每秒

**Comment by kkHAIKE** [comment]
你 chrome + 插件 + 直接点击下载不用其他工具  也会是 503？

**Comment by xepo12** [comment]
chrome不行。
115强制使用115浏览器，其他浏览器都不行

**Comment by kkHAIKE** [comment]
你在说啥。。。。。
反正我试了试是没问题。。。感觉你使用姿势问题。。
大家都是 chrome 用的

**Comment by xepo12** [comment]
我的年费账号不能用chrome下载，
普通115账号可以chrome + 插件 + 直接点击下载
