### ISSUE TITLE
选择文件按钮始终和界面菜单重合，参考旧issue无法解决

### ISSUE THREAD

**Issue by MFYDev** [kkHAIKE/fake115#88]
### 我能否访问/Ping通 rawgit.com (最近地方 DNS 有屏蔽此域名)

能

### 我是否点击了主界面 "使用帐号登录"，重复刷新了几次

0

### 我的操作系统是，版本是

Win10 最新版

### 我的浏览器是，版本是

Chrome  87.0.4280.88（正式版本）

### 我的油猴插件是(Violent/Grease/Tamper)monkey，版本是

4.11最新版

### 我遇到了什么问题，截图

选择文件按钮依然和115界面冲突，参考 #76 无效
![image](https://user-images.githubusercontent.com/53750381/103392265-fa639400-4b57-11eb-8f15-62b61c3cde6b.png)

**Comment by kkHAIKE** [comment]
可以试试不使用插件，因为现在官方已经支持密码登入了
