### ISSUE TITLE
一直正在登录,无限转圈

### ISSUE THREAD

**Issue by ZiPenOk** [kkHAIKE/fake115#9]
F12内容如下

url: 115.com/ storageName：FyqWzDurPTNZu rule: default
util-min.js?v=1472190160:1 115浏览器状态
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 Array[2] "加载bridge-q"
VM106:233 url: q.115.com/bridge_assets.html storageName：LEWEKgBqlpHV rule: default
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 Array[2] "加载bridge-q-成功 https://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1472261766768_0&_t1472261766768 : https://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1472261766768_0&_t1472261766768"
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 Array[3] "https://q.115.com/bridge_assets.html?cb_key=iframe_cb_key__1472261766768_0&_t1472261766768"
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 Array[2] "加载bridge-qrcode"
VM112:233 url: qrcodeapi.115.com/bridge_assets.html storageName：XBAHQaqJgESsEpnKlT rule: default
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 Array[2] "加载bridge-qrcode-成功 https://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1472261767513_1&_t1472261767513 : https://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1472261767513_1&_t1472261767513"
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 Array[3] "https://qrcodeapi.115.com/bridge_assets.html?cb_key=iframe_cb_key__1472261767513_1&_t1472261767513"

VM96:10822 Uncaught TypeError: Cannot read property 'cookie' of undefined

??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 ["//msg.115.com/bridge_assets.html", "msg"] "加载bridge-msg"
VM176:233 url: msg.115.com/bridge_assets.html storageName：tjVyQICDwDNH rule: default
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 ["//msg.115.com/bridge_assets.html", "msg"] "加载bridge-msg-成功 https://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1472261789277_3&_t1472261789277 : https://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1472261789277_3&_t1472261789277"
??libs/jquery-1.7.2.min.js,jquery-extend.min.js,libs/json2.min.js,oofUtil.min.js,paths.min.js,oofUt…:4 ["//msg.115.com/bridge_assets.html", "msg", "load"] "https://msg.115.com/bridge_assets.html?cb_key=iframe_cb_key__1472261789277_3&_t1472261789277"

**Comment by kkHAIKE** [comment]
Uncaught TypeError: Cannot read property 'cookie' of undefined
看起来你的浏览器不能使用 document.cookie ？不会吧

**Comment by ZiPenOk** [comment]
用的centbrowser,也有人使用正常的,就是不知道我出在什么地方

**Comment by kkHAIKE** [comment]
有防护类的插件吗，禁止cookies之类的

**Comment by ZiPenOk** [comment]
我试着禁用全部插件,就留脚本,还是不行

**Comment by kkHAIKE** [comment]
centbrowser 2.0.10.57 测试通过。请尝试还原默认设置

**Comment by jackiejtr** [comment]
我和他问题一样- -

**Comment by kkHAIKE** [comment]
请详细说下版本
我是官网下载的centbrowser最新win版加上插件商店的tampermonkey插件

**Comment by jackiejtr** [comment]
chrome 49以及360极速最新都这问题、、

**Comment by kkHAIKE** [comment]
增加了输出异常信息，使用后反馈下

**Comment by jamwee1987** [comment]
最新的猎豹浏览器也不行 一直在无限转圈

**Comment by sino1641** [comment]
chrome 56 也出现同样情况，重启浏览器就好（kill掉所有进程）

**Comment by kkHAIKE** [comment]
https://github.com/kkHAIKE/fake115/issues/14
