### ISSUE TITLE
无法下载文件夹

### ISSUE THREAD

**Issue by xtynk** [kkHAIKE/fake115#94]
### 我能否访问/Ping通 rawgit.com (最近地方 DNS 有屏蔽此域名)
能

### 我是否点击了主界面 "使用帐号登录"，重复刷新了几次
是

### 我的操作系统是，版本是
Win10 1909专业版

### 我的浏览器是，版本是
Firefox 88.0.1

### 我的油猴插件是(Violent/Grease/Tamper)monkey，版本是
Tamper 4.13

### 我遇到了什么问题，截图
选择文件夹点下载无反应，只能单个文件下载。

**Comment by kkHAIKE** [comment]
可以多选下载，没有实现下载文件夹功能
