### ISSUE TITLE
下载失效

### ISSUE THREAD

**Issue by xtynk** [kkHAIKE/fake115#97]
我能否访问/Ping通 rawgit.com (最近地方 DNS 有屏蔽此域名)
能
我是否点击了主界面 "使用帐号登录"，重复刷新了几次
是
我的操作系统是，版本是
Windows 10 专业版 21H1
我的浏览器是，版本是
Firefox 96.0
我的油猴插件是(Violent/Grease/Tamper)monkey，版本是
Tamper 4.1.3
### 我的控制台日志如下 (firefox 用户请拷贝 Ctrl+Shift+J 界面中的内容)

我遇到了什么问题，截图
点击下载弹出提示 undefined
![snipaste_20220114_132916](https://user-images.githubusercontent.com/19271092/149456731-d120c394-88b6-4e19-a28d-c779a4a4c6cf.png)

**Comment by kkHAIKE** [comment]
控制台有什么输出吗

**Comment by xtynk** [comment]
> 控制台有什么输出吗

提交issue之后一直没试过，刚才登上去发现居然可以下载了……
